// Bakes WW2 maps (Natural Earth 50m via world-atlas) into assets/maps/eu.js:
// for each view, one land path plus grouped country paths in 1920x1080 space,
// and the projection parameters (see assets/lib/geo.js). Borders are modern
// shapes grouped to read as 1939 (Kaliningrad → Germany as East Prussia, etc.).
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoMercator, geoPath } from "d3-geo";

const W = 1920, H = 1080;
const topo = JSON.parse(readFileSync(new URL("./node_modules/world-atlas/countries-50m.json", import.meta.url)));
const land = feature(topo, topo.objects.land);
const countries = feature(topo, topo.objects.countries).features;
const byId = Object.fromEntries(countries.map((f) => [f.id, f]));
const GROUPS = {
  de: ["276"], pl: ["616"], fr: ["250"], uk: ["826"], it: ["380"], es: ["724"], pt: ["620"],
  ussr: ["643", "804", "112", "498"], cz: ["203", "703"], at: ["040"], fi: ["246"], no: ["578"],
  se: ["752"], dk: ["208"], benl: ["056", "528", "442"], ch: ["756"], gr: ["300"], al: ["008"],
  yu: ["191", "070", "688", "499", "807", "705", "-99"], ro: ["642"], hu: ["348"], bg: ["100"],
  tr: ["792"], ie: ["372"], baltic: ["440", "428", "233"], eg: ["818"], ly: ["434"], tn: ["788"],
  dz: ["012"], ma: ["504"], et: ["231"], er: ["232"], so: ["706"], sd: ["729", "728"], sa: ["682"],
};
const polysOf = (f) => (f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates);
const meanLon = (poly) => { const r = poly[0]; return r.reduce((a, p) => a + p[0], 0) / r.length; };
function group(ids) {
  let polys = [];
  for (const id of ids) { const f = byId[id]; if (f) polys.push(...polysOf(f)); }
  return polys;
}
const G = {};
for (const [k, ids] of Object.entries(GROUPS)) G[k] = group(ids);
// East Prussia: Russia's Kaliningrad exclave belongs with Germany in 1939
G.de.push(...G.ussr.filter((p) => meanLon(p) < 23 && p[0][0][1] > 54));
G.ussr = G.ussr.filter((p) => !(meanLon(p) < 23 && p[0][0][1] > 54));

const VIEWS = {
  europe: { center: [16, 51.5], scale: 1750 },
  west: { center: [5, 49.5], scale: 3300 },
  uk: { center: [-3.2, 54.3], scale: 4300 },
  med: { center: [16, 37.5], scale: 2000 },
  east: { center: [33, 52], scale: 2000 },
  horn: { center: [28, 23], scale: 1350 },
};
const out = {};
for (const [name, v] of Object.entries(VIEWS)) {
  const proj = geoMercator().center(v.center).scale(v.scale).translate([W / 2, H / 2]).clipExtent([[-80, -80], [W + 80, H + 80]]);
  const path = geoPath(proj).digits(1);
  const c = {};
  for (const [k, polys] of Object.entries(G)) { const d = path({ type: "MultiPolygon", coordinates: polys }); if (d) c[k] = d; }
  out[name] = { center: v.center, scale: v.scale, land: path(land), c };
}
const js = "// Generated by tools/bake-map.mjs — Natural Earth 50m, Mercator, grouped for 1939.\nglobalThis.EU = " + JSON.stringify(out) + ";\n";
writeFileSync(new URL("../assets/maps/eu.js", import.meta.url), js);
console.log("bytes", js.length, Object.fromEntries(Object.entries(out).map(([k, v]) => [k, Object.keys(v.c).length])));
