// Bakes the Mediterranean coastline (Natural Earth 50m via world-atlas) into
// assets/maps/med.json: one land path in 1920x1080 space + the projection
// parameters so places/routes can be projected the same way (see assets/lib/geo.js).
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoMercator, geoPath } from "d3-geo";

const W = 1920, H = 1080;
const topo = JSON.parse(readFileSync(new URL("./node_modules/world-atlas/land-50m.json", import.meta.url)));
const land = feature(topo, topo.objects.land);
// Frame: Atlantic coast of Spain → Aegean; Alps → Saharan edge.
const CENTER = [13.5, 38.6], SCALE = 2050;
const proj = geoMercator().center(CENTER).scale(SCALE).translate([W / 2, H / 2])
  .clipExtent([[-60, -60], [W + 60, H + 60]]);
const path = geoPath(proj).digits(1);
const d = path(land);
writeFileSync(new URL("../assets/maps/med.json", import.meta.url),
  JSON.stringify({ width: W, height: H, center: CENTER, scale: SCALE, land: d }));
writeFileSync(new URL("../assets/maps/med.js", import.meta.url),
  "// Generated by tools/bake-map.mjs — Natural Earth 50m land, Mercator.\nglobalThis.MED = " +
  JSON.stringify({ width: W, height: H, center: CENTER, scale: SCALE, land: d }) + ";\n");
const tl = proj.invert([0, 0]), br = proj.invert([W, H]);
console.log("bytes", d.length, "lon/lat corners", tl.map(n=>n.toFixed(1)), br.map(n=>n.toFixed(1)));
for (const [n, ll] of Object.entries({ Rome: [12.48, 41.9], Carthage: [10.32, 36.85], NewCarthage: [-0.98, 37.6], Saguntum: [-0.27, 39.68] }))
  console.log(n, proj(ll).map(Math.round));
