// Act 3 (frames 34–43) and Act 4 (frames 44–55) cue sheets. Format: see cues.mjs / cues-act2.mjs.
const N = (text, x = {}) => ({ who: "NARRATOR", text, ...x });
export const VOICES_A34 = {
  SAILOR: ["am_puck", 1.25], ARCHIMEDES: ["bm_lewis", 1.1, "en-gb"], MOTHER: ["af_bella", 1.08],
  MASINISSA: ["am_fenrir", 1.0], CATO: ["bm_daniel", 1.05, "en-gb"], GAIUS: ["am_eric", 1.1],
};
export const META_A34 = { "34": { lead: 3.4, intro: "act" }, "44": { lead: 3.4, intro: "act" } };
export const FRAMES_A34 = {
  // ---------------- ACT 3 ----------------
  "34": [
    N("After Cannae, any normal country would have asked for peace. Carthage gets its islands back, Rome keeps its city, everybody goes home for dinner. Hannibal was counting on it. Except… no."),
    { who: "HANNIBAL", text: "So. Shall we discuss terms?", add: [200, 400, 440, "bl", 40], el: "hannibal" },
    { who: "FLACCUS", text: "No.", add: [1460, 420, 200, "br", 64], el: "flaccus" },
    { who: "HANNIBAL", text: "You lost eighty thousand men.", add: [160, 400, 480, "bl", 40], el: "hannibal" },
    { who: "FLACCUS", text: "Dennis?", add: [1400, 420, 260, "br", 46], el: "flaccus" },
    { who: "DENNIS", text: "Sir… we're out of legions.", add: [1120, 120, 420, "br", 40], pip: ["dennis", "dennis", 1640, 200, "DENNIS (ACCOUNTS)"] },
    { who: "FLACCUS", text: "…Okay. Make more legions.", add: [1240, 420, 440, "br", 40], el: "flaccus", keep: true },
  ],
  "35": [
    N("Rome refused to discuss peace.", { at: ["st-a"] }),
    N("Refused to pay ransom for its own captured soldiers.", { at: ["st-b"] }),
    N("Banned mourning for longer than thirty days.", { at: ["st-c"] }),
    N("Bought eight thousand slaves, armed them, and sent them to fight.", { at: ["st-d@0.3"] }),
    N("Rome did not know how to lose. It was honestly a bit scary."),
  ],
  "36": [
    N("But Cannae did change some minds! Big, rich Capua switched to Hannibal.", { at: ["capua@0.6"], sfx: [["ding", 1.6]] }),
    N("King Philip the Fifth of Macedon signed up.", { at: ["r-mac@0.3", "macedon@0.3"] }),
    N("And Syracuse, in Sicily, switched too… and Syracuse had a secret weapon. His name was Archimedes.", { at: ["syracuse@0.1", "st-team@0.6"] }),
  ],
  "37": [
    { who: "SAILOR", text: "Is this normal?! Is this a normal thing for the ocean to do?!", add: [380, 580, 520, "bl", 38], el: "sailor", move: [["claw", 0.0, { dr: -4 }, 0.6]], sfx: [["boing", 0.2]] },
    N("Archimedes built giant cranes that grabbed Roman ships out of the water and flipped them over! Rome besieged Syracuse for two years anyway, took it, and in the chaos a Roman soldier killed Archimedes. The story goes he was in the middle of a maths problem.", { at: ["circles@0.75"] }),
    { who: "ARCHIMEDES", text: "Excuse me, you're standing on my circles.", add: [180, 420, 500, "bl", 40], el: "arch2", keep: true },
    N("Rome, as usual, said sorry by taking all his stuff."),
  ],
  "38": [
    N("Meanwhile, Hannibal had a problem. He had no siege equipment, not enough men, and he couldn't take the big walled cities. So he wrote home."),
    { who: "HANNIBAL", text: "Dear Carthage. Winning. Need men. Love, Hannibal.", el: "hannibal", at: ["letter-1"] },
    { who: "HANNO", text: "No.", add: [1500, 360, 200, "bl", 64], el: "hanno" },
    { who: "HANNIBAL", text: "Dear Carthage. Still winning. Really need men.", el: "hannibal", at: ["letter-2"] },
    { who: "HANNO", text: "No.", add: [1520, 380, 200, "bl", 64], el: "hanno" },
    { who: "HANNIBAL", text: "Dear Carthage. Please.", el: "hannibal", at: ["letter-3"] },
    { who: "HANNO", text: "No.", add: [1500, 360, 200, "bl", 64], el: "hanno" },
    { who: "HANNIBAL", text: "Dear Hanno. I know what you're going to say.", add: [160, 120, 560, "bl", 38], el: "hannibal" },
    { who: "HANNO", text: "…Yes?", add: [1480, 360, 240, "bl", 54], el: "hanno" },
    { who: "HANNIBAL", text: "\"…Yes?\" Ha. Got you.", add: [200, 120, 440, "bl", 42], el: "hannibal" },
    { who: "HANNO", text: "No.", add: [1500, 360, 200, "bl", 64], el: "hanno", keep: true, sfx: [["slam", 0.1]] },
  ],
  "39": [
    N("Rome went back to Fabius's plan: never fight Hannibal. Fight everyone near Hannibal. In 211, Rome besieged Capua. And to pull them away, Hannibal marched right up to Rome itself.", { at: ["camp@0.8", "hannibal@0.8"] }),
    { who: "MOTHER", text: "Eat your vegetables, or Hannibal's going to get you!", add: [860, 120, 540, "br", 38], el: "mother", at: ["mother", "kid"] },
    N("\"Hannibal ad portas!\" Hannibal is at the gates! Roman parents scared kids with that for centuries!", { at: ["st-portas@0.1"] }),
    N("But Rome did not move a single soldier from Capua. Instead, says Livy, they auctioned off the land Hannibal was camped on. And somebody bought it. At full price.", { at: ["sale@0.6"] }),
    { who: "HANNIBAL", text: "They sold my tent?", add: [560, 520, 360, "bl", 42], el: "hannibal" },
    { who: "MAGO", text: "To a man named Gaius. He'd like you off his lawn.", add: [1100, 560, 520, "br", 38] },
    N("Hannibal left. Capua fell.", { move: [["hannibal", 0.2, { dx: -900 }, 1.6]] }),
  ],
  "40": [
    N("And in Spain, Rome was losing. Both Scipio brothers — including our consul from the Rhône — were killed there in 211.", { at: ["graves@0.3"] }),
    N("Rome needed a new commander in Spain. Nobody volunteered. Except one twenty-five-year-old.", { at: ["senators", "flaccus"] }),
    { who: "PUBLIUS", text: "Me! I'll do it!", add: [260, 300, 320, "bl", 48], el: "publius", at: ["publius"] },
    { who: "FLACCUS", text: "Who are you?", add: [1300, 380, 330, "br", 42], el: "flaccus" },
    { who: "PUBLIUS", text: "The kid! From the river! You were all told to remember me!", add: [180, 280, 560, "bl", 36], el: "publius", at: ["ptr@0.5"], sfx: [["ding", 1.4]] },
    { who: "FLACCUS", text: "Okay. More… kid.", add: [1280, 380, 360, "br", 42], el: "flaccus", keep: true },
  ],
  "41": [
    N("Publius Cornelius Scipio studied Hannibal like homework. He marched on New Carthage, Carthage's capital in Spain, and found out from local fishermen that the lagoon behind the city got shallow in the evening.", { at: ["front@0.6"] }),
    N("Nobody would ever attack across the lagoon. So he attacked across the lagoon! His men waded over while everyone was busy defending the front wall, and he took the city in a single day!", { at: ["waders@0.2", "st-day@0.85"], move: [["waders", 0.25, { dx: -560, dy: 100 }, 3.0]] }),
    { who: "PUBLIUS", text: "Surprise from an unexpected direction. Hannibal does that. I just… also did that.", add: [1100, 560, 600, "br", 36], el: "publius", keep: true },
  ],
  "42": [
    N("Meanwhile Hannibal's other brother, Hasdrubal, slipped out of Spain with an army and crossed the Alps too! Much faster this time — the paths were all broken in.", { at: ["route2"] }),
    N("But the Romans captured his messengers, read the plan, and two Roman armies ganged up on him at the Metaurus River. Hasdrubal was killed.", { at: ["msg@0.2", "metaurus@0.7"], sfx: [["stab", 0.25]] }),
    N("The Romans threw his head into Hannibal's camp."),
    N("That is how Hannibal found out.", { at: ["sad"] }),
  ],
  "43": [
    N("In 206, Scipio crushed Carthage's last big army in Spain. Spain was Rome's.", { at: ["st-ilipa", "r-spain-r@0.75"] }),
    N("And Hannibal — still never beaten in a major battle in Italy — was stuck down in the toe of the boot.", { at: ["toe@0.6"] }),
    { who: "SURUS", text: "Are we there yet?", add: [1260, 560, 380, "br", 42], el: "surus" },
    { who: "HANNIBAL", text: "…No.", add: [1000, 640, 200, "br", 52], el: "hannibal" },
    { who: "SURUS", text: "Is there a beach in the toe?", add: [1220, 560, 460, "br", 40], el: "surus" },
    { who: "MAGO", text: "There's a beach. Romans are standing on it.", add: [140, 160, 520, "bl", 38], keep: true },
  ],
  // ---------------- ACT 4 ----------------
  "44": [
    N("Scipio came home a hero, got elected consul, and had a big idea."),
    { who: "PUBLIUS", text: "Hannibal came to our house. So let's go to HIS house.", add: [140, 420, 540, "bl", 38], el: "publius", at: ["africa-map"] },
    { who: "FABIUS", text: "That's reckless.", add: [1300, 440, 360, "br", 42], el: "fabius" },
    { who: "PUBLIUS", text: "It's what Hannibal would do.", add: [180, 440, 440, "bl", 40], el: "publius" },
    { who: "FABIUS", text: "Yes! That's why it's reckless!", add: [1220, 440, 480, "br", 40], el: "fabius", keep: true },
  ],
  "45": [
    N("The senate gave him Sicily and permission… but hardly any army. So he took volunteers, plus the survivors of Cannae, who'd been shipped off to Sicily in disgrace for losing.", { at: ["st-cannae@0.6"] }),
    N("They really, really wanted a rematch. In 204 BC, they landed in Africa.", { at: ["ships@0.5"], sfx: [["whoosh", 2.0]] }),
  ],
  "46": [
    N("There, he found an ally: Masinissa, a Numidian prince, with the best cavalry in the world, and a huge grudge against Carthage's ally, King Syphax.", { at: ["masinissa", "cav@0.4", "st-mas@0.5"], sfx: [["gallop", 1.0]] }),
    { who: "MASINISSA", text: "I hate Syphax. He stole my kingdom. And my fiancée.", add: [1080, 440, 520, "br", 38], el: "masinissa" },
    { who: "PUBLIUS", text: "I'll get you the kingdom.", add: [300, 440, 420, "bl", 40], el: "publius" },
    { who: "MASINISSA", text: "…And the fiancée?", add: [1180, 460, 380, "br", 42], el: "masinissa" },
    { who: "PUBLIUS", text: "Let's focus on the kingdom.", add: [280, 440, 440, "bl", 40], el: "publius", keep: true },
  ],
  "47": [
    N("Scipio burned Syphax's camps in a night attack, beat Carthage in the field, and suddenly Carthage was very, very worried.", { at: ["flames@0.2", "panic@0.82"], sfx: [["boom", 0.8]] }),
    { who: "HANNO", text: "Bring Hannibal home! Send ships! Send ALL the ships!", add: [360, 340, 520, "bl", 40] },
    { who: "MAGO", text: "Oh, NOW we're sending stuff?", add: [1180, 380, 500, "br", 40], el: "gisgo2", keep: true },
  ],
  "48": [
    N("And so, after fifteen years in Italy — fifteen years! — never once beaten in a major battle there… Hannibal sailed home.", { at: ["st-15@0.4"], move: [["boat", 0.3, { dx: 260 }, 5.0]] }),
    { who: "SURUS", text: "Sand. Sun. Waves. Is it…?", add: [1160, 340, 420, "bl", 42], el: "surus" },
    { who: "HANNIBAL", text: "Yes, Surus. It's a beach.", add: [300, 340, 440, "bl", 40] },
    { who: "SURUS", text: "It's the most beautiful thing I've ever seen.", add: [1120, 340, 520, "bl", 38], el: "surus", keep: true },
    N("He got about a week.", { stk: [960, 900, "HE GOT ABOUT A WEEK.", 50, 3] }),
  ],
  "49": [
    N("In 202 BC, near Zama, the two greatest generals alive actually met, face to face, before the battle! Hannibal — older now, one eye — offered peace.", { at: ["st-zama", "armies"] }),
    { who: "HANNIBAL", text: "You're young. You've been lucky. Luck runs out.", add: [160, 420, 520, "bl", 38], el: "hannibal" },
    { who: "PUBLIUS", text: "I'm a big fan, by the way. I read everything about you.", add: [1160, 400, 540, "br", 38], el: "publius" },
    { who: "HANNIBAL", text: "…Everything?", add: [260, 460, 320, "bl", 44], el: "hannibal" },
    { who: "PUBLIUS", text: "Took notes.", add: [1300, 440, 300, "br", 44], el: "publius" },
    { who: "HANNIBAL", text: "Oh no.", add: [300, 460, 240, "bl", 48], el: "hannibal", keep: true, sfx: [["sting", 0.3]] },
  ],
  "50": [
    N("Hannibal had eighty brand-new elephants!", { at: ["herd"], count: [["el-counter", 0.2, 1, 81]], sfx: [["rumble", 0.3]] }),
    N("But Scipio had studied him for years. He lined his men up with lanes in between the units.", { at: ["lanes@0.6"] }),
    N("When the elephants charged, every Roman blew every horn and trumpet they had. The elephants freaked out.", { at: ["horns@0.5"], move: [["herd", 0.15, { dy: 320 }, 2.2]], sfx: [["sting", 2.6]] }),
    N("Lots of them ran straight down the lanes and out the back! Some turned around and trampled Carthage's own cavalry.", { move: [["herd", 0.1, { dy: 900, o: 0 }, 2.6]], count: [["el-counter", 0.6, 81, 1]] }),
    { who: "SURUS", text: "Rookies.", add: [1440, 380, 280, "br", 48], el: "surus", keep: true, at: ["surus"] },
  ],
  "51": [
    N("The infantry fought for hours. And then Masinissa and the Roman cavalry came charging back, and slammed into Hannibal's rear.", { at: ["c-inf", "r-inf", "cav-a@0.5"], move: [["cav-a", 0.6, { dx: 560, dy: -560 }, 1.4], ["cav-b", 0.6, { dx: -560, dy: -560 }, 1.4]], sfx: [["crash", 5.0]] }),
    N("Wait. Surround them. Hit them from behind. Hannibal had seen this one before. He invented it.", { at: ["cav-b"], stk: [960, 960, "INSTANT REPLAY: CANNAE", 46, -2] }),
    { who: "PUBLIUS", text: "I copied your homework.", add: [440, 160, 420, "bl", 42], el: "pip-p", at: ["pip-p"] },
    { who: "HANNIBAL", text: "You got a better grade.", add: [1060, 160, 440, "br", 42], el: "pip-h", at: ["pip-h"], keep: true },
  ],
  "52": [
    N("Rome gave Scipio a new name: Scipio Africanus! Carthage surrendered in 201 BC, and Rome sent the bill.", { at: ["st-af"] }),
    N("Lose Spain.", { at: ["st-a"] }),
    N("Lose your navy, except ten ships.", { at: ["st-b"] }),
    N("Ten thousand talents, over fifty years.", { at: ["st-c"] }),
    N("And never start a war again — ever — without Rome's permission.", { at: ["st-d"], stk: [1500, 820, "+ COMPLAINING FEE", 40, 4] }),
    { who: "HANNO", text: "Can we at least—", add: [240, 560, 380, "bl", 40], el: "hanno" },
    { who: "FLACCUS", text: "No.", add: [1460, 580, 200, "br", 64], el: "flaccus" },
    { who: "HANNO", text: "…Oh. Oh, I don't like that at all.", add: [180, 560, 520, "bl", 38], el: "hanno" },
    { who: "FLACCUS", text: "Oh, I LOVE that.", add: [1300, 580, 360, "br", 42], el: "flaccus", keep: true },
  ],
  "53": [
    N("And Hannibal? He went home, got elected to high office, cracked down on corruption, and fixed Carthage's money so well that Carthage offered to pay off the fifty-year debt early.", { at: ["coins@0.6", "st-paid@0.8"], sfx: [["ding", 8.0]] }),
    { who: "FLACCUS", text: "Dennis. That's suspicious.", add: [1030, 360, 420, "br", 40], el: "flaccus-pip", at: ["flaccus-pip"] },
    { who: "DENNIS", text: "Sir, it's money.", add: [1080, 600, 320, "br", 42], pip: ["dennis", "dennis", 1680, 700, "DENNIS (ACCOUNTS)"] },
    { who: "FLACCUS", text: "Suspicious money.", add: [1100, 380, 360, "br", 42], el: "flaccus-pip" },
    N("Rome pushed him into exile. He spent years advising Rome's enemies, all the way from Syria to the Black Sea.", { at: ["exile@0.05"], hide: ["flaccus-pip", "dennis"] }),
    N("And in 183 BC, with Roman agents closing in, he took poison, rather than be handed over. The same year, Scipio Africanus died too — in exile, bitter at the Romans he had saved."),
  ],
  "54": [
    N("As for Carthage, an old Roman senator named Cato started ending every speech — on any subject — with the same sentence.", { at: ["cato", "audience"] }),
    { who: "CATO", text: "…and that is why the figs are overpriced. Also, Carthage must be destroyed.", el: "cato", at: ["figs@0.1", "st-delenda@0.7"] },
    N("Fifty years later, it was. But that's another war.", { at: ["st-146@0.4"] }),
  ],
  "55": [
    N("Hannibal won almost every battle. Rome won the war. Because Rome never, ever quit. And because one kid did his homework.", { at: ["board"] }),
    { who: "HANNIBAL", text: "Can I see the replay now?", add: [200, 560, 460, "bl", 40] },
    N("You just watched it."),
    { who: "SURUS", text: "Are we there yet?", add: [1280, 520, 380, "br", 42], el: "surus" },
    N("Yes, Surus. We're there.", { at: ["end@0.6"], sfx: [["sting", 1.4]] }),
  ],
};
