// Act 1 cue sheet: every spoken line, who says it, and what it triggers on screen.
// line: { who, text, b?: existing bubble id, add?: [x, y, w, tail, size] new bubble,
//         el?: speaker element id (bobs while talking), keep?: true, at?: [ids revealed at line start],
//         sfx?: [[name, offsetSec]] }
// Bubble text defaults to the spoken text. Ids are local to the frame (builder prefixes them).
export const VOICES = {
  NARRATOR: ["bm_george", 1.2, "en-gb"], HANNIBAL: ["am_onyx", 1.04], KID: ["af_sky", 1.16],
  HAMILCAR: ["am_fenrir", 1.1], GISGO: ["am_puck", 1.19], SURUS: ["am_santa", 0.95],
  HANNO: ["bm_lewis", 0.99, "en-gb"], FLACCUS: ["bm_fable", 1.1, "en-gb"], SCIPIO: ["am_michael", 1.16],
  PUBLIUS: ["am_echo", 1.16], ENVOY: ["bm_daniel", 1.04, "en-gb"], SAGUNTINE: ["am_liam", 1.21],
  CARTH: ["am_eric", 1.1], HASDRUBAL: ["am_adam", 1.01], SPY: ["am_eric", 1.26], TRIBESMAN: ["am_liam", 1.1],
};
const N = (text, x = {}) => ({ who: "NARRATOR", text, ...x });

export const FRAMES = {
  "01": [
    N("This man is Hannibal Barca. He invaded Italy with elephants, beat Rome in battle after battle, and won a victory so total that generals still study it today.", { at: ["board"] }),
    N("He lost.", { at: ["box-5", "st-lost"], sfx: [["slam", 0]] }),
    { who: "HANNIBAL", text: "I'd like to see the replay.", b: "b-replay", el: "surus" },
    N("This is the Second Punic War.", { at: ["title"], sfx: [["sting", 0]] }),
  ],
  "02": [
    N("In one corner: Rome. Likes roads, laws, and everything that isn't Rome yet.", { at: ["r-rome", "flaccus"] }),
    N("In the other: Carthage, a rich North African trading city with the best navy around.", { at: ["r-carth", "carth"] }),
    { who: "FLACCUS", text: "Nice island you've got there.", b: "b1", el: "flaccus", at: ["sicily-ring"] },
    { who: "CARTH", text: "It's Sicily. It's ours.", b: "b2", el: "carth" },
    { who: "FLACCUS", text: "For now.", b: "st-fornow", el: "flaccus", keep: true, sfx: [["slam", 0]] },
  ],
  "03": [
    N("They'd already fought once: the First Punic War, twenty-three years, mostly over Sicily. Rome had no real navy, so they found a wrecked Carthaginian warship and copied it. Plank. By. Plank.", { at: ["copy@0.6", "tape@0.6", "st-plank@0.86"] }),
    { who: "GISGO", text: "Hey, that's ours!", b: "offscreen" },
    N("Then Rome lost entire fleets. Not to Carthage. To storms.", { at: ["storm"], sfx: [["thunder", 0.4]] }),
    { who: "FLACCUS", text: "Okay. More ships.", add: [1300, 560, 420, "br", 40], el: "copier" },
    N("And by being too stubborn to stop, Rome won. Carthage lost Sicily, and got a massive bill.", { at: ["st-win"] }),
  ],
  "04": [
    N("Then Carthage couldn't pay its mercenaries, who attacked Carthage.", { at: ["mercs"] }),
    N("While it was busy, Rome took Sardinia. And Corsica.", { at: ["hand@0.25", "islands@0.25"], sfx: [["whoosh", 0.6]] }),
    { who: "CARTH", text: "Hey! You can't just—", add: [120, 560, 460, "br", 40] },
    { who: "FLACCUS", text: "We're borrowing them.", add: [1330, 70, 470, "bl", 40], el: "flaccus" },
    { who: "CARTH", text: "For how long?", add: [160, 720, 380, "br", 40] },
    { who: "FLACCUS", text: "Forever-ish.", b: "b-forever", el: "flaccus" },
    N("When Carthage complained, Rome added another twelve hundred talents to the bill. For complaining.", { at: ["invoice"], sfx: [["slam", 1.0]] }),
  ],
  "05": [
    N("Nobody took this harder than Hamilcar Barca. \"Barca\" meant lightning. His hobbies were Rome, and hating Rome.", { at: ["board", "strings"] }),
    { who: "HAMILCAR", text: "Everything connects back to them. The islands. The fee. My lower back pain.", add: [80, 60, 520, "br", 36], el: "hamilcar" },
    N("Carthage's senate, led by a man called Hanno, was over it.", { at: ["hanno-win"] }),
    { who: "HAMILCAR", text: "Send me to Spain. I'll conquer it, dig up the silver, pay off Rome. Purely financial.", add: [80, 60, 560, "br", 34], el: "hamilcar" },
    { who: "HANNO", text: "…Is this a revenge thing?", add: [1380, 340, 480, "bl", 38], el: "hanno-win" },
    { who: "HAMILCAR", text: "Purely. Financial.", b: "b-fin", el: "hamilcar" },
    { who: "HANNO", text: "No.", b: "b-no", el: "hanno-win", keep: true },
    N("He went anyway."),
  ],
  "06": [
    { who: "HAMILCAR", text: "Hannibal. Do you want to come to Spain with Daddy?", add: [240, 240, 560, "br", 38], el: "hamilcar", at: ["flame"] },
    { who: "KID", text: "Yes!", add: [1200, 360, 220, "bl", 56], el: "kid" },
    { who: "HAMILCAR", text: "Then put your hand on the altar and swear eternal hatred of Rome.", add: [200, 220, 620, "br", 36], el: "hamilcar" },
    { who: "KID", text: "…Is there a version of Spain without the hatred?", b: "b-version", el: "kid" },
    { who: "HAMILCAR", text: "No.", b: "b-no", el: "hamilcar" },
    { who: "KID", text: "…I swear.", add: [1220, 380, 300, "bl", 46], el: "kid" },
    N("This really happened. Most kids that age get a pet.", { at: ["split"], sfx: [["whoosh", 0]] }),
    N("Hannibal got a grudge. He kept it forever.", { at: ["split-r"] }),
  ],
  "07": [
    N("In Spain, Hamilcar built a new empire: silver mines, tough soldiers, elephants.", { at: ["r-spain", "coins"], sfx: [["ding", 1.2]] }),
    { who: "SPY", text: "Carthage. Getting rich again. Also — elephants.", b: "b-spy", el: "spy", at: ["bush", "spy"] },
    N("Then, retreating from a battle, Hamilcar drowned in a river.", { at: ["river"], sfx: [["splash", 1.8]] }),
    { who: "HAMILCAR", text: "Remember — hate Rome! And feed the elephants!", add: [520, 180, 640, "bl", 40], keep: true },
  ],
  "08": [
    N("Next came his son-in-law, known as Hasdrubal the Handsome. Not \"the Brave.\" Not \"the Wise.\" The Handsome.", { at: ["hasdrubal", "st-name@0.3", "sparkles"], sfx: [["ding", 0.4]] }),
    N("He signed a deal with Rome: Carthage stays south of the River Ebro.", { at: ["ebro", "ebro-label", "flaccus"] }),
    { who: "FLACCUS", text: "Not one toe over this line.", b: "b-toe", el: "flaccus" },
    { who: "HASDRUBAL", text: "Wouldn't dream of it, darling.", b: "b-darling", el: "hasdrubal" },
    N("Then a servant with a personal grudge assassinated him. The Barca family had a lot of problems. Most were grudges.", { at: ["dagger"], sfx: [["stab", 0.9]] }),
  ],
  "09": [
    N("In 221 BC, the army picked a new commander: Hannibal, twenty-six. The kid from the altar.", { at: ["lift"], sfx: [["cheer", 0.2]] }),
    N("Still angry.", { at: ["flash", "st-angry"], sfx: [["slam", 0]] }),
    N("The soldiers loved him. He slept on the ground in his cloak, next to the sentries."),
    { who: "GISGO", text: "He sleeps on the ground? I have a bed. Now I feel bad about my bed.", add: [1150, 640, 560, "br", 34], keep: true },
  ],
  "10": [
    N("South of the Ebro sat Saguntum. Saguntum was friends with Rome.", { at: ["town"] }),
    { who: "SAGUNTINE", text: "We're friends with Rome! Rome will protect us!", add: [1120, 560, 520, "br", 38], el: "saguntine-happy" },
    N("Hannibal attacked it anyway.", { at: ["fires", "smoke", "saguntine"], sfx: [["boom", 0.2]] }),
    N("The siege lasted eight months. Rome, its very good friend, sent…", { at: ["calendar", "letter"] }),
    { who: "SAGUNTINE", text: "\"Thoughts and prayers. — Rome.\"", el: "saguntine" },
    N("Saguntum fell."),
  ],
  "11": [
    N("So Rome sent envoys to Carthage, to demand Hannibal be handed over.", { at: ["senate", "envoy"] }),
    { who: "ENVOY", text: "In this fold of my toga, I carry peace — and war. Choose!", add: [1120, 260, 600, "bl", 38], el: "envoy", at: ["fold"] },
    { who: "HANNO", text: "You keep war in your toga?", add: [380, 300, 440, "bl", 38], el: "hanno" },
    { who: "ENVOY", text: "Yes.", add: [1120, 360, 200, "bl", 50], el: "envoy" },
    { who: "HANNO", text: "What else is in there?", b: "b-what", el: "hanno" },
    { who: "ENVOY", text: "…Snacks. Choose!", b: "b-snacks", el: "envoy" },
    { who: "CARTH", text: "You choose.", add: [1300, 120, 320, "bl", 44], el: "senate" },
    { who: "ENVOY", text: "Then I give you… war!", add: [1120, 300, 460, "bl", 44], el: "envoy", keep: true },
    N("That really happened. The Second Punic War began in 218 BC. With a toga.", { at: ["st-war"], sfx: [["slam", 0]] }),
  ],
  "12": [
    N("Rome owned the sea. The plan: one army sails to Spain, one to Africa. Easy.", { at: ["sea-plans"] }),
    { who: "FLACCUS", text: "Where's he going to go? He can't sail. He can't fly.", add: [1180, 70, 640, "bl", 36], at: ["flaccus-pip"] },
    N("Hannibal's plan was simpler.", { at: ["hannibal", "gisgo"] }),
    { who: "HANNIBAL", text: "We walk.", add: [1100, 640, 260, "br", 48], el: "hannibal", at: ["route", "x1", "x2"], sfx: [["whoosh", 0]] },
    { who: "GISGO", text: "Sir. Those are mountains.", b: "b-mtn", el: "gisgo" },
    { who: "HANNIBAL", text: "Yes.", add: [1150, 720, 180, "br", 46], el: "hannibal" },
    { who: "GISGO", text: "Big ones.", add: [1520, 620, 260, "br", 44], el: "gisgo" },
    { who: "HANNIBAL", text: "Yes.", add: [1150, 720, 180, "br", 46], el: "hannibal" },
    { who: "GISGO", text: "With snow on.", add: [1480, 620, 320, "br", 44], el: "gisgo" },
    { who: "HANNIBAL", text: "It'll be fine.", b: "b-fine", el: "hannibal", keep: true },
    N("It would not be fine.", { at: ["st-notfine"], sfx: [["scratch", 0]] }),
  ],
  "13": [
    N("Hannibal set off with ninety thousand infantry, twelve thousand cavalry, and thirty-seven elephants.", { at: ["army", "cnt-0@0.18", "cnt-1@0.45", "cnt-2@0.72"] }),
    N("This is Surus. Surus has no idea what he signed up for.", { at: ["surus", "surus-label"], sfx: [["boing", 0.4]] }),
    { who: "SURUS", text: "Are we going to the beach?", b: "b-beach", el: "surus" },
    { who: "HANNIBAL", text: "Sort of.", b: "b-sort", el: "hannibal", keep: true, at: ["hannibal", "el-counter"] },
  ],
  "14": [
    N("First, the Pyrenees, fighting tribes the whole way. Thousands of soldiers wanted out. So Hannibal just… sent them home.", { at: ["deserters"] }),
    { who: "GISGO", text: "Wait, we were allowed to leave?", b: "b-leave", el: "gisgo" },
    { who: "HANNIBAL", text: "Not you.", b: "b-notyou", el: "hannibal", keep: true },
  ],
  "15": [
    N("Next, the Rhône. Elephants hate water, so engineers built huge rafts covered in dirt, so they'd think it was land.", { at: ["raft"] }),
    { who: "SURUS", text: "This is ground.", add: [300, 340, 400, "br", 44], el: "surus" },
    { who: "SURUS", text: "…The ground is moving.", b: "b-moving", el: "surus" },
    N("Some panicked and jumped in. Turns out elephants can swim, using their trunks as snorkels. Everyone learned something that day.", { at: ["snorkel", "st-swim"], sfx: [["splash", 0.3]] }),
  ],
  "16": [
    N("Meanwhile, the consul Publius Scipio raced to the Rhône to stop him.", { at: ["ship"] }),
    { who: "SCIPIO", text: "Hannibal! Surrender in the name of— oh.", add: [240, 240, 560, "br", 40], el: "scipio", at: ["scipio"] },
    N("He arrived three days after Hannibal had left.", { at: ["st-late", "tumbleweed"], sfx: [["wind", 0]] }),
    { who: "SCIPIO", text: "It's still warm.", b: "b-warm", el: "scipio", keep: true, at: ["dung"] },
  ],
  "17": [
    N("And then: the Alps. In autumn. With elephants.", { at: ["peaks"], sfx: [["wind", 0]] }),
    N("Snow, ice, landslides, narrow paths over enormous drops. Many of his men had never seen snow. They hated it immediately.", { at: ["column", "surus", "mule"] }),
    { who: "GISGO", text: "Sir, it's very cold.", add: [220, 470, 420, "br", 40], el: "gisgo", at: ["gisgo", "hannibal"] },
    { who: "HANNIBAL", text: "Think warm thoughts.", add: [1140, 520, 440, "bl", 40], el: "hannibal" },
    { who: "GISGO", text: "My warm thought is Spain, sir.", b: "b-warm", el: "gisgo", keep: true },
  ],
  "18": [
    N("The mountain tribes didn't love an army marching through their home, so they rolled rocks onto it.", { at: ["gauls", "rocks"], sfx: [["rumble", 1.5]] }),
    { who: "TRIBESMAN", text: "Strike!", b: "score", el: "gauls", keep: true, sfx: [["crash", 0]] },
    N("He fought through, but lost a lot of men.", { at: ["aah"] }),
  ],
  "19": [
    N("At one point a rock blocked the path. Livy says they lit a fire against it, poured sour wine on, and cracked it apart.", { at: ["rock"] }),
    { who: "HANNIBAL", text: "First, heat your rock for several hours.", add: [120, 300, 560, "br", 38], el: "chef", at: ["banner", "chef"], sfx: [["sting", 0]] },
    { who: "HANNIBAL", text: "Then, a generous splash of vinegar.", add: [120, 300, 560, "br", 38], el: "chef", at: ["vinegar"] },
    { who: "HANNIBAL", text: "…And smash.", b: "b-smash", el: "chef", sfx: [["crack", 0.6]] },
    N("Is that true? Historians argue about it. Is it awesome? Historians do not argue about that."),
  ],
  "20": [
    N("Fifteen days later, they stumbled into Italy. Of ninety thousand infantry… about twenty thousand were left. Six thousand cavalry. And thirty-seven elephants—", { at: ["army", "cnt-0@0.3", "cnt-1@0.62", "cnt-2@0.85"] }),
    N("—who somehow mostly made it. Nobody knows how.", { at: ["surus"] }),
    { who: "SURUS", text: "That was a terrible beach.", b: "b-beach", el: "surus" },
    N("He'd lost most of his army. But he was in Italy, and Rome hadn't seen it coming, because nobody had ever done anything this stupid before."),
  ],
  "21": [
    { who: "FLACCUS", text: "He did WHAT? He walked?! Over the ALPS?!", el: "senate", at: ["senate"], sfx: [["spit", 0.5]] },
    N("Scipio rushed back and met Hannibal's cavalry at the Ticinus River. It went badly.", { at: ["numidians", "dust", "scipio"], sfx: [["gallop", 0]] }),
    N("Scipio was wounded, and only saved when his seventeen-year-old son charged in and dragged him out.", { at: ["publius"] }),
    { who: "PUBLIUS", text: "Dad! I've got you!", add: [80, 300, 420, "bl", 42], el: "publius" },
    { who: "SCIPIO", text: "Publius?! You're supposed to be guarding the baggage!", add: [560, 300, 620, "bl", 36], el: "scipio" },
    { who: "PUBLIUS", text: "You're welcome.", b: "b-welcome", el: "publius", keep: true, at: ["ptr"] },
  ],
  "22": [
    N("Hannibal was in Italy. The local Gauls, who hated Rome, flocked to join him.", { at: ["fires"] }),
    { who: "FLACCUS", text: "Okay. More legions.", b: "flaccus-pip", el: "flaccus-pip" },
    N("Rome was about to learn just how bad this was going to get."),
    { who: "SURUS", text: "Are we there yet?", b: "b-yet", el: "surus", keep: true },
    { who: "HANNIBAL", text: "Not even close.", b: "b-close", el: "surus", keep: true, at: ["endcard"], sfx: [["sting", 1.0]] },
  ],
};
