// Bakes WW2 maps (Natural Earth via world-atlas) into assets/maps/eu.js:
// for each view, one land path plus grouped country paths in 1920x1080 space,
// and the projection parameters (see assets/lib/geo.js). Borders are modern
// shapes grouped to read as 1939–43 (Kaliningrad → Germany as East Prussia, etc.).
// Episode 2 adds: world (1942 hook), pacific, south (Volga/Caucasus), stalingrad,
// africa and ladoga views. Every view is a rotated Mercator, so the Pacific views
// cross the antimeridian cleanly.
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoMercator, geoPath } from "d3-geo";

const W = 1920, H = 1080;
const load = (res) => {
  const topo = JSON.parse(readFileSync(new URL(`./node_modules/world-atlas/countries-${res}.json`, import.meta.url)));
  const countries = feature(topo, topo.objects.countries).features;
  return { land: feature(topo, topo.objects.land), byId: Object.fromEntries(countries.map((f) => [f.id, f])) };
};
const DATA = { "50m": load("50m"), "110m": load("110m") };
const GROUPS = {
  de: ["276"], pl: ["616"], fr: ["250"], uk: ["826"], it: ["380"], es: ["724"], pt: ["620"],
  ussr: ["643", "804", "112", "498", "268", "051", "031", "398", "795", "860", "762", "417"], cz: ["203", "703"], at: ["040"], fi: ["246"], no: ["578"],
  se: ["752"], dk: ["208"], benl: ["056", "528", "442"], ch: ["756"], gr: ["300"], al: ["008"],
  yu: ["191", "070", "688", "499", "807", "705", "-99"], ro: ["642"], hu: ["348"], bg: ["100"],
  tr: ["792"], ie: ["372"], baltic: ["440", "428", "233"], eg: ["818"], ly: ["434"], tn: ["788"],
  dz: ["012"], ma: ["504"],
  // Asia / Pacific
  jp: ["392"], kr: ["410", "408"], tw: ["158"], cn: ["156"], mn: ["496"], ph: ["608"], my: ["458", "096", "702"],
  idn: ["360", "626"], th: ["764"], mm: ["104"], ic: ["704", "418", "116"], png: ["598"], au: ["036"], nz: ["554"],
  sol: ["090"], ind: ["356", "050", "144", "524", "064", "586"],
  // Americas, Middle East
  us: ["840"], ca: ["124"], mx: ["484"], me: ["364", "368", "682", "760", "422", "400", "376", "275", "887", "512", "784", "414", "634", "048"],
};
const polysOf = (f) => (f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates);
const meanLon = (poly) => { const r = poly[0]; return r.reduce((a, p) => a + p[0], 0) / r.length; };
function groups(res) {
  const { byId } = DATA[res], G = {};
  for (const [k, ids] of Object.entries(GROUPS)) { G[k] = []; for (const id of ids) { const f = byId[id]; if (f) G[k].push(...polysOf(f)); } }
  // East Prussia: Russia's Kaliningrad exclave belongs with Germany
  G.de.push(...G.ussr.filter((p) => meanLon(p) < 23 && p[0][0][1] > 54));
  G.ussr = G.ussr.filter((p) => !(meanLon(p) < 23 && p[0][0][1] > 54));
  return G;
}
const GG = { "50m": groups("50m"), "110m": groups("110m") };

// keep in sync with assets/lib/geo.js
const VIEWS = {
  europe: { center: [16, 51.5], scale: 1750 },
  west: { center: [5, 49.5], scale: 3300 },
  atlantic: { center: [-35, 47], scale: 900, res: "110m" },
  med: { center: [16, 37.5], scale: 2000 },
  east: { center: [33, 52], scale: 2000 },
  world: { center: [75, 22], scale: 380, res: "110m" },
  pacific: { center: [165, 18], scale: 700 },
  south: { center: [42, 46.2], scale: 4200 },
  stalingrad: { center: [43.6, 48.75], scale: 13000 },
  africa: { center: [12, 32.5], scale: 2350 },
  ladoga: { center: [31.2, 60.25], scale: 9500 },
  usa: { center: [-104, 39], scale: 1900 },
};
const only = process.argv.slice(2);
const prev = (() => { try { const src = readFileSync(new URL("../assets/maps/eu.js", import.meta.url), "utf8"); return JSON.parse(src.slice(src.indexOf("=") + 1).trim().replace(/;$/, "")); } catch { return {}; } })();
const out = {};
for (const [name, v] of Object.entries(VIEWS)) {
  if (only.length && !only.includes(name) && prev[name]) { out[name] = prev[name]; continue; }
  const res = v.res || "50m";
  const proj = geoMercator().rotate([-v.center[0], 0]).center([0, v.center[1]]).scale(v.scale).translate([W / 2, H / 2]).clipExtent([[-80, -80], [W + 80, H + 80]]);
  const path = geoPath(proj).digits(v.scale > 5000 ? 1 : v.scale < 500 ? 0 : 1);
  const c = {};
  for (const [k, polys] of Object.entries(GG[res])) { if (!polys.length) continue; const d = path({ type: "MultiPolygon", coordinates: polys }); if (d) c[k] = d; }
  out[name] = { center: v.center, scale: v.scale, land: path(DATA[res].land), c };
}
const js = "// Generated by tools/bake-map.mjs — Natural Earth 50m/110m, rotated Mercator, grouped for 1939–43.\nglobalThis.EU = " + JSON.stringify(out) + ";\n";
writeFileSync(new URL("../assets/maps/eu.js", import.meta.url), js);
console.log("bytes", js.length, Object.fromEntries(Object.entries(out).map(([k, v]) => [k, [Object.keys(v.c).length, (JSON.stringify(v).length / 1024).toFixed(0) + "k"]])));
