// Episode 2 cue sheet ("The Year Hitler Started Losing"): every spoken line, who says it, and what it triggers.
// line: { who, text, pre?: pause before the line (s), add?: [x, y, w, tail, size] speech bubble, el?: speaker element (bobs),
//         keep?, at?: ["id@frac" | "id@+sec"], sfx?: [[name, offsetSec | "+sec"]], move?: [[id, frac, {dx,dy,dr,ds,o}, dur]],
//         hide?: [ids], cam?: [[frac, scale, px, py, dur]], pip?: [id, preset, x, y, label], stk?: [x, y, text, size, rot] }
// A frac may be "+x": x seconds after the line ends. Long narration paragraphs from SCRIPT.md are split into
// consecutive N() lines (text kept verbatim). Recurring characters use Episode 1's voices and reference clips.
export const VOICES = {
  NARRATOR: ["bm_george", 1.0, "en-gb"], HITLER: ["am_adam", 1.12], STALIN: ["bm_lewis", 0.92, "en-gb"],
  MUSSOLINI: ["am_fenrir", 1.08], ENZO: ["am_echo", 1.0], CHURCHILL: ["bm_daniel", 0.92, "en-gb"], FDR: ["am_eric", 1.1],
  KLAUS: ["am_puck", 1.1], AIDESU: ["am_michael", 1.05], PILOT: ["am_echo", 1.1],
  TOJO: ["am_onyx", 1.05], YAMAMOTO: ["am_michael", 0.95], SOVOFF: ["am_liam", 1.1], RADAR: ["am_liam", 1.2],
  DUTY: ["am_adam", 0.95], PILOTUS: ["am_puck", 1.05], DOOLITTLE: ["am_eric", 1.0], CODEBREAKERUS: ["am_liam", 0.95],
  CODEBREAKERUK: ["bm_fable", 1.0, "en-gb"], UBOAT: ["am_fenrir", 1.0], ROMMEL: ["am_santa", 1.0],
  GERSOLDIER: ["am_echo", 1.15], SOVSOLDIER: ["am_eric", 1.15], CHUIKOV: ["am_santa", 0.92],
};
const N = (text, x = {}) => ({ who: "NARRATOR", text, ...x });
const L = (who, text, x = {}) => ({ who, text, ...x });
const BACK = [0, 1.0, 960, 540, 0.05];
const TP = { tail: 3.4, reveals: [["cut-tp", -3.0], ["st-tp", -2.6]], sfx: [["boom", -3.0, 0.8], ["slam", -2.6, 0.7]] };

export const META = {
  "01": { tail: 3.0 },
  "02": { drop: [] },
  "03": { drop: ["stalin-pt"] },
  "04": { tail: 2.4 },
  "07": { drop: ["pop-factory"], cams: [{ t: 0, s: 2.0, px: 960, py: 690, d: 0.01 }] },
  "10": TP,
  "14": { tail: 2.4 },
  "19": TP,
  "22": { tail: 2.2 },
  "23": { tail: 2.4 },
  "24": { tail: 4.2, reveals: [["endcard", -3.6]] },
};

const stagger = (prefix, n, a, b) => Array.from({ length: n }, (_, i) => `${prefix}${i}@${(a + ((b - a) * i) / Math.max(1, n - 1)).toFixed(3)}`);

export const FRAMES = {
  "01": [
    N("Summer, 1942.", { at: ["pop-axisbox"] }),
    N("Germany rules Europe from France almost to Moscow.", { at: ["fade-axE@0.1"], cam: [[0, 1.7, 600, 330, 1.0]] }),
    N("Japan has taken an empire across the Pacific in six months.", { at: ["fade-axJ@0.1"], cam: [[0, 1.6, 1420, 480, 1.2]] }),
    N("The Axis is winning everywhere.", { cam: [[0, 1.0, 960, 540, 1.0]] }),
    N("One year later, it's losing everywhere.", { at: ["fade-back", ...stagger("arr-b", 5, 0.1, 0.6)], hide: ["pop-axisbox"] }),
    N("And it all turns on three battles.", { at: ["pop-tp1@0.35", "pop-tp2@0.55", "pop-tp3@0.75"], sfx: [["boom", 0.6]] }),
    N("But first: mud.", { at: ["cut-mud", "title@+0.7"], sfx: [["splash", 0], ["sting", "+0.8"]] }),
  ],
  "02": [
    N("Germany's invasion of the Soviet Union went terrifyingly well.", { at: ["fade-map", "arr-g0@0.2", "arr-g1@0.3", "arr-g2@0.4"], sfx: [["rumble", 0.3]] }),
    N("Millions of Soviet soldiers killed or captured.", { at: ["st-mil@0.1"] }),
    N("By October, the Germans were nearing Moscow.", { cam: [[0.1, 1.6, 1120, 340, 1.0]] }),
    N("Then the autumn rains came.", { move: [["fade-map", 0, { o: 0 }, 0.2]], at: ["storm", "st-date@0.4"], cam: [BACK], sfx: [["thunder", 0.2]] }),
    L("KLAUS", "Sir, the tanks are stuck.", { add: [460, 450, 440, "br", 42], el: "klaus" }),
    L("HITLER", "Unstick them!", { add: [1180, 210, 360, "br", 46], pip: ["pip-h", "hitler", 1680, 330, "RADIO"], hide: ["st-date"] }),
    L("KLAUS", "Sir, good news. The mud is gone.", { add: [420, 430, 480, "br", 40], el: "klaus", at: ["fade-snow", "fade-snow2"], hide: ["pip-h", "a-5"], sfx: [["wind", 0]] }),
    L("HITLER", "Excellent!", { add: [1220, 210, 320, "br", 46], pip: ["pip-h2", "hitler", 1680, 330, "RADIO"] }),
    L("KLAUS", "It froze. The tanks are still in it.", { add: [420, 430, 480, "br", 40], el: "klaus", hide: ["pip-h2", "a-7"], cam: [[0.35, 1.3, 1100, 640, 0.5]] }),
    N("The army had no winter uniforms.", { at: ["cut-cold"], cam: [BACK] }),
    N("It had planned to be finished before winter.", { at: ["pop-note@0.4"] }),
    N("In December, fresh Soviet troops counterattacked outside Moscow and drove the Germans back.", { at: ["fade-map2", "arr-s0@0.35", "arr-s1@0.45"], cam: [[0.25, 1.5, 1120, 360, 1.4]], sfx: [["boom", 2.5]] }),
  ],
  "03": [
    N("Before that, with the Germans close to the city, Stalin stayed in Moscow, and held the annual military parade in Red Square anyway.", { at: ["st-date"], move: [["march", 0, { dx: 260 }, 9]] }),
    L("SOVOFF", "Comrade Stalin, after the parade, where do the troops go?", { add: [600, 20, 560, "bl", 38], el: "sovoff" }),
    L("STALIN", "That way.", { add: [250, 60, 260, "br", 44], move: [["stalin", 0, { o: 0 }, 0.05], ["stalin-pt", 0, { o: 1 }, 0.05]], at: ["pop-sign@0.6"] }),
    L("SOVOFF", "That's the front.", { add: [620, 60, 380, "bl", 42], el: "sovoff" }),
    L("STALIN", "Yes. It's very close. Saves time.", { add: [110, 20, 420, "br", 40], keep: true, cam: [[0, 1.5, 300, 40, 0.4]] }),
    N("Many of the soldiers marched from the parade straight into battle.", { cam: [BACK], move: [["march", 0.1, { dx: 2000 }, 5]], hide: ["a-4"] }),
  ],
  "04": [
    N("Behind the front, Nazi Germany was carrying out the Holocaust.", { at: ["fade-ttl@0.2"] }),
    N("In the occupied Soviet Union, killing squads shot Jewish men, women and children in mass executions, more than a million people by the end of 1942.", { at: ["fade-occ@0.1", "cnt-squads@0.72"] }),
    N("In January 1942, Nazi officials met at a villa in Wannsee to coordinate what they called the \"Final Solution\": the murder of every Jew in Europe.", { at: ["fade-doc"], hide: ["cnt-squads"] }),
    N("From across the continent, Jews were deported by train to death camps in occupied Poland.", { hide: ["fade-doc", "fade-occ"], at: ["fade-routes", ...stagger("arr-r", 12, 0.05, 0.55), ...stagger("pop-k", 6, 0.6, 0.9)] }),
    N("By 1945, about six million Jews had been murdered, along with millions of others the Nazis persecuted, among them Roma, disabled people, Soviet prisoners of war and Poles.", { at: ["cnt-6m@0.08", "fade-others@0.45"] }),
  ],
  "05": [
    N("On the other side of the world, Japan had been at war in China since 1937, a war that had already cost millions of Chinese lives, including the massacre at Nanjing.", { at: ["fade-china"] }),
    N("Then America cut off Japan's oil.", { at: ["cut-oil", "st-oil@0.55"] }),
    L("TOJO", "The plan. Step one: seize the oil fields of Southeast Asia.", { add: [40, 380, 420, "bl", 36], el: "tojo", hide: ["cut-oil", "fade-china"], at: ["st-date", "pop-s1@0.45"], stk: [330, 300, "HIDEKI TOJO", 34, -3] }),
    L("YAMAMOTO", "Good.", { add: [1500, 440, 240, "br", 46], el: "yama", stk: [1640, 330, "ADMIRAL YAMAMOTO", 32, 3], hide: ["st-k2", "st-date"] }),
    L("TOJO", "Step two: destroy the American fleet so they can't interfere.", { add: [40, 380, 420, "bl", 36], el: "tojo", at: ["pop-s2@0.35"], hide: ["st-k3"] }),
    L("YAMAMOTO", "And step three?", { add: [1480, 430, 380, "br", 42], el: "yama" }),
    L("TOJO", "Step three: America gets sad and goes home.", { add: [40, 380, 420, "bl", 36], el: "tojo", at: ["pop-s3@0.3"], hide: ["a-5"], cam: [[0.35, 1.3, 0, 420, 0.5]] }),
    L("YAMAMOTO", "Have you been to America?", { add: [1420, 420, 440, "br", 40], el: "yama", cam: [BACK] }),
    L("TOJO", "No.", { add: [200, 470, 200, "bl", 50], el: "tojo" }),
    L("YAMAMOTO", "I have.", { add: [1500, 440, 260, "br", 46], el: "yama", keep: true, cam: [[0, 1.4, 1500, 700, 0.4]] }),
    N("Admiral Yamamoto predicted Japan could \"run wild\" for six months, maybe a year, and after that he had no confidence at all.", { cam: [BACK], hide: ["a-9"], stk: [960, 820, "\"RUN WILD\": 6 MONTHS, MAYBE A YEAR", 34, -2] }),
    N("Then he planned the attack.", { at: ["pop-plan@0.3"], hide: ["st-k10"] }),
  ],
  "06": [
    N("On the morning of December 7th, 1941, Japanese planes attacked the US Pacific Fleet at Pearl Harbor.", { at: ["st-date", "inr-planes@0.45"], sfx: [["whoosh", 4]] }),
    L("RADAR", "Sir, there's a huge group of planes on the radar. Heading this way.", { add: [560, 430, 390, "bl", 36], el: "radar", at: ["cut-radar", "pop-blip@0.3"] }),
    L("DUTY", "Don't worry about it.", { add: [1100, 470, 440, "br", 40], el: "duty" }),
    N("He assumed it was a flight of American bombers due in from California.", { hide: ["a-1", "a-2"], at: ["pop-b17@0.3"] }),
    N("Eight battleships were damaged or sunk.", { hide: ["cut-radar"], at: ["fires@0.05", "st-8@0.5"], sfx: [["boom", 0.1], ["boom", 1.0]] }),
    N("About two thousand four hundred Americans were killed.", { at: ["cnt-killed@0.1"] }),
    N("But that morning, America's aircraft carriers were out at sea.", { at: ["cut-sea@0.15", "cut-shop@+0.2", "pop-open@+1.1"], move: [["sign-old", "+0.7", { o: 0 }, 0.3]], sfx: [["whoosh", "+0.7"]] }),
    L("FDR", "Yesterday, December 7th, 1941, a date which will live in infamy…", { pre: 1.6, add: [560, 400, 640, "br", 38] }),
    N("America declared war on Japan."),
    N("And four days later, Hitler, who was not required to, declared war on America.", { at: ["cut-hq@0.25"], sfx: [["slam", 1.0]] }),
    L("KLAUS", "Sir. Why?", { add: [1180, 450, 300, "br", 44] }),
    L("HITLER", "Solidarity!", { add: [380, 430, 340, "bl", 46] }),
    L("KLAUS", "With who?", { add: [1200, 450, 280, "br", 44] }),
    L("HITLER", "…Japan?", { pre: 0.7, add: [400, 440, 260, "bl", 46] }),
    L("KLAUS", "They didn't tell us they were attacking, sir.", { add: [1000, 420, 520, "br", 38], keep: true, cam: [[0.2, 1.35, 1250, 700, 0.4]] }),
  ],
  "07": [
    N("America's secret weapon was boring: factories.", { at: ["pop-factory@0.5"], move: [["shop", 0.5, { o: 0 }, 0.3]], cam: [[0.45, 1.0, 960, 540, 1.2]] }),
    N("Car plants built tanks.", { at: ["inl-tanks"], sfx: [["rumble", 0]] }),
    N("Millions of women went to work building planes.", { at: ["pop-planes@0.2", "inl-workers@0.4"] }),
    L("KLAUS", "Sir, the Americans say they built ninety-six thousand aircraft this year.", { add: [860, 420, 560, "br", 38], el: "klaus", at: ["cut-hq"] }),
    L("HITLER", "Propaganda!", { add: [380, 440, 360, "bl", 46], el: "hitler" }),
    L("KLAUS", "There's a photograph, sir.", { add: [1100, 470, 420, "br", 40], el: "klaus", at: ["pop-photo@0.3"] }),
    L("HITLER", "Fake!", { add: [400, 440, 220, "bl", 50], el: "hitler" }),
    L("KLAUS", "It's a very large parking lot, sir. Full of planes.", { add: [1000, 470, 500, "br", 38], el: "klaus", move: [["pop-photo", 0.05, { dr: 94, ds: 1.3 }, 0.5]], at: ["cut-lot@0.62"], sfx: [["whoosh", 0.05]] }),
    N("At home, about a hundred and twenty thousand Japanese Americans, most of them US citizens, were forced into internment camps.", { at: ["fade-intern", ...stagger("pop-j", 10, 0.2, 0.6), "cnt-int@0.7"] }),
    N("None was ever convicted of spying. The government apologized in 1988.", { at: ["pop-apology@0.5"] }),
  ],
  "08": [
    N("Exactly as Yamamoto predicted, Japan won almost everywhere for six months.", { at: ["cut-map", "st-date@0.3"] }),
    N("Hong Kong.", { at: ["arr-hk"], cam: [[0, 1.4, 60, 560, 0.8]] }),
    N("The Philippines.", { at: ["arr-ph", "fade-ph@0.4"] }),
    N("Singapore, where some eighty thousand British Empire troops surrendered, the largest surrender in British history.", { at: ["arr-sg", "fade-my@0.15", "st-sg@0.55", "arr-dei@0.7", "fade-dei@0.78", "arr-bu@0.85", "fade-bu@0.9"] }),
    L("YAMAMOTO", "Five months… six months.", { add: [1100, 430, 420, "br", 40], el: "yama", hide: ["cut-map", "st-date"], at: ["cut-cal6@0.6"], cam: [BACK] }),
    L("TOJO", "We're winning!", { add: [220, 440, 380, "bl", 44], el: "tojo" }),
    L("YAMAMOTO", "…Six months is up.", { add: [1120, 430, 400, "br", 42], el: "yama", at: ["pop-x6@0.5"], keep: true, cam: [[0, 1.3, 1200, 560, 0.4]] }),
  ],
  "09": [
    N("America needed good news.", { at: ["st-date"] }),
    N("So in April 1942, sixteen army bombers, far too big to land on an aircraft carrier, took off from one, and bombed Tokyo.", { at: ["st-16@0.15"], hide: ["st-date"] }),
    L("PILOTUS", "Colonel, how do we land back on the carrier?", { add: [760, 150, 480, "br", 38], el: "pilot", hide: ["st-16"] }),
    L("DOOLITTLE", "We don't.", { add: [1500, 170, 260, "bl", 46], el: "dool" }),
    L("PILOTUS", "Then where do we land?", { add: [800, 180, 440, "br", 40], el: "pilot" }),
    L("DOOLITTLE", "China. Ish.", { add: [1440, 170, 300, "bl", 46], el: "dool", keep: true, cam: [[0, 1.35, 1400, 450, 0.4]], at: ["fade-route@+0.15"] }),
    N("The damage was small.", { cam: [BACK, [0.1, 1.8, 650, 300, 0.8]] }),
    N("The humiliation was huge."),
    N("It pushed Japan into its next gamble.", { cam: [BACK], at: ["fade-gamble", "arr-mid@0.3", "pop-q@0.8"] }),
  ],
  "10": [
    N("June 1942.", { at: ["st-date"] }),
    N("Japan planned to finish off the US Navy near a tiny island called Midway.", { cam: [[0.5, 1.6, 1080, 350, 0.8]], hide: ["st-date"] }),
    N("American codebreakers knew an attack was coming on a target called \"AF\".", { cam: [BACK], at: ["pop-af@0.75"] }),
    N("But where was AF?", { at: ["pop-afq@0.2"] }),
    L("CODEBREAKERUS", "Tell Midway to send a fake message: \"Our water machine is broken.\"", { add: [60, 440, 560, "bl", 36], el: "cb", at: ["pop-msg@0.6"] }),
    N("Japanese radio picked it up and reported: AF is short of water.", { at: ["cut-int"], sfx: [["ding", 0.3]] }),
    L("CODEBREAKERUS", "Thank you.", { add: [300, 470, 300, "bl", 44], el: "cb", hide: ["cut-int", "pop-afq"], at: ["pop-afok"], keep: true, cam: [[0, 1.35, 640, 600, 0.4]] }),
    N("American dive bombers caught the Japanese carriers with decks full of planes and fuel.", { at: ["fade-battle"], cam: [BACK], move: [["dive", 0.1, { dy: 200, dx: 60 }, 5]] }),
    N("In about five minutes, three carriers were burning.", { at: ["st-5m@0.1", "pop-f0@0.3", "pop-f1@0.45", "pop-f2@0.6"], sfx: [["boom", 1.0], ["boom", 1.7], ["boom", 2.4]] }),
    N("Japan lost four, and never took the initiative in the Pacific again.", { at: ["pop-f3@0.15", "st-4@0.3"], sfx: [["boom", 0.4]] }),
    N("Two months later, the Marines landed on Guadalcanal, and started pushing back.", { at: ["fade-guad", "arr-guad@0.35"] }),
  ],
  "11": [
    N("In the Atlantic, German U-boats hunted the convoys Britain needed to survive.", { at: ["pop-ub@0.4"] }),
    N("But at a country house called Bletchley Park, codebreakers, among them Alan Turing, were reading the German Enigma code.", { at: ["fade-house", "pop-tur@0.45"] }),
    L("UBOAT", "New orders. We will attack the convoy at—", { add: [300, 420, 560, "bl", 38], el: "uboat", at: ["cut-split"] }),
    L("CODEBREAKERUK", "—grid square forty-two, at dawn.", { add: [1180, 420, 520, "br", 38], el: "cbuk", at: ["pop-paper@0.3"] }),
    L("UBOAT", "How did—", { add: [300, 440, 300, "bl", 44], el: "uboat" }),
    L("CODEBREAKERUK", "—he know. Yes.", { add: [1300, 440, 400, "br", 42], el: "cbuk", keep: true, cam: [[0, 1.4, 1500, 640, 0.4]] }),
    N("Thousands of Allied ships were sunk.", { at: ["fade-cost"], cam: [BACK] }),
    N("But around three quarters of all U-boat crewmen never came home.", { at: ["fade-ub3@0.2"] }),
  ],
  "12": [
    N("In North Africa, Erwin Rommel, the \"Desert Fox\", chased the British deep into Egypt.", { at: ["fade-m1", "arr-rom@0.35"] }),
    N("The desert war was really about one thing.", { hide: ["fade-m1"], at: ["st-date"], stk: [1300, 560, "ERWIN ROMMEL", 34, 3], cam: [[0.55, 1.6, 860, 860, 0.6]] }),
    L("KLAUS", "Sir. A quarter of a tank.", { add: [170, 440, 400, "br", 40], el: "klausd", cam: [BACK], hide: ["st-k1", "st-date"] }),
    L("ROMMEL", "We'll capture British fuel.", { add: [880, 430, 440, "br", 40], el: "rommel" }),
    L("KLAUS", "That's not a supply plan, sir.", { add: [150, 430, 420, "br", 40], el: "klausd" }),
    L("ROMMEL", "It's worked before.", { add: [900, 440, 400, "br", 42], el: "rommel" }),
    L("KLAUS", "Once, sir.", { add: [290, 460, 280, "br", 46], el: "klausd", keep: true, cam: [[0, 1.4, 560, 760, 0.4]] }),
    N("In late 1942, the British under Bernard Montgomery beat Rommel at El Alamein.", { at: ["fade-m2", "pip-mont@0.3", "arr-mont@0.5"], cam: [BACK], sfx: [["boom", 3]] }),
    N("Days later, Americans and British landed in Morocco and Algeria.", { hide: ["pip-mont"], at: ["arr-t1@0.2", "arr-t2@0.3", "arr-t3@0.4"] }),
    N("By May 1943, the Axis was out of Africa.", { at: ["arr-t4@0.1", "st-may@0.6", "cut-tp@+0.5", "st-tp@+0.9", "cut-ban@+3.3"], move: [["cut-tp", "+3.3", { o: 0 }, 0.01]], sfx: [["boom", "+0.5"], ["slam", "+0.9"]] }),
    L("MUSSOLINI", "Enzo! \"VICTORY IN AFRICA\"!", { pre: 3.6, add: [880, 40, 480, "br", 40], el: "muss" }),
    L("ENZO", "Fill it in yourself.", { add: [360, 470, 420, "br", 42], el: "enzo", at: ["pop-blank@0.2"], keep: true }),
  ],
  "13": [
    N("America's shop was supplying the Soviets too: hundreds of thousands of trucks, millions of boots, and a mountain of tinned meat.", { at: ["st-date", "pop-trucks@0.45", "pop-boots@0.65", "pop-tins@0.85"], sfx: [["pop", 5], ["pop", 7]] }),
    L("AIDESU", "Comrade Stalin, the Americans have sent… meat. In a tin.", { add: [1180, 430, 520, "br", 38], el: "aide", hide: ["st-date"] }),
    L("STALIN", "I trust nobody.", { add: [700, 450, 380, "br", 44], el: "stalin" }),
    L("AIDESU", "It's called Spam.", { add: [1240, 450, 420, "br", 42], el: "aide" }),
    L("STALIN", "…I trust Spam.", { add: [700, 450, 360, "br", 44], el: "stalin", keep: true, cam: [[0, 1.4, 1000, 640, 0.4]] }),
    N("Years later, Soviet leader Nikita Khrushchev admitted that without Spam, they'd have struggled to feed their army.", { at: ["cut-memo@0.3"], cam: [BACK] }),
  ],
  "14": [
    N("In the north, Leningrad was besieged for almost nine hundred days.", { at: ["fade-city", "arr-ger@0.3", "arr-fin@0.4", "fade-lines@0.55", "fade-days@0.75"] }),
    N("At the worst point, civilians got a hundred and twenty-five grams of bread a day.", { at: ["fade-card@0.2"] }),
    N("Around eight hundred thousand civilians died, most of them of starvation.", { at: ["cnt-civ@0.1"] }),
    N("Food came in over a road of ice across Lake Ladoga.", { at: ["arr-road@0.2", "fade-road@0.5"] }),
    N("The city never surrendered."),
  ],
  "15": [
    N("In summer 1942, Hitler sent his armies south, for the oil fields of the Caucasus.", { at: ["st-date", "arr-sta@0.3", "arr-cau@0.45", "pop-oil@0.75"] }),
    L("KLAUS", "Yes! Oil! Finally!", { add: [140, 470, 400, "bl", 44], el: "klaus", hide: ["st-date"] }),
    L("HITLER", "And that city.", { add: [1300, 430, 380, "br", 44], el: "hitler", at: ["pop-ring@0.5"] }),
    L("KLAUS", "Why that city?", { add: [140, 470, 380, "bl", 44], el: "klaus" }),
    L("HITLER", "It has his name on it.", { add: [1220, 420, 460, "br", 42], el: "hitler", keep: true, cam: [[0, 1.3, 1400, 700, 0.4]] }),
    N("Stalingrad was a big industrial city on the Volga.", { at: ["cut-city"], cam: [BACK] }),
    N("It was also named after Stalin.", { cam: [[0.1, 1.5, 820, 240, 0.5]] }),
    N("Which meant neither dictator would ever let the other one have it.", { cam: [BACK] }),
    L("STALIN", "Not one step back.", { add: [180, 330, 480, "bl", 44], at: ["cut-split"], sfx: [["slam", 0]] }),
    L("HITLER", "Not one step back!", { add: [1260, 330, 480, "br", 44], sfx: [["slam", 0]] }),
    L("KLAUS", "…This is going to be bad.", { add: [760, 560, 420, "bl", 40], at: ["pop-kmid"], hide: ["a-8", "a-9"], keep: true, cam: [[0.3, 1.35, 960, 760, 0.4]] }),
  ],
  "16": [
    N("German bombers flattened the city.", { at: ["fade-bomb", "fires@0.3"], sfx: [["boom", 0.6], ["boom", 1.4]] }),
    N("Then the army fought into it, street by street, house by house, floor by floor.", { hide: ["fade-bomb"], at: ["st-date@0.1"], cam: [[0.4, 1.25, 960, 600, 1.4], [0.8, 1.5, 960, 720, 0.8]] }),
    N("The Soviets clung to a strip along the river, with fresh men ferried across under fire every night.", { at: ["fade-strip", "pop-boat0@0.55", "pop-boat1@0.65", "pop-boat2@0.75"], cam: [BACK], move: [["pop-boat0", 0.6, { dx: -380 }, 3], ["pop-boat1", 0.7, { dx: -330 }, 3], ["pop-boat2", 0.8, { dx: -420 }, 3]] }),
    L("GERSOLDIER", "We have the kitchen!", { add: [330, 380, 420, "bl", 40], el: "gsol", hide: ["fade-strip", "st-date"], cam: [[0, 1.5, 960, 720, 0.05]] }),
    L("SOVSOLDIER", "We have the bathroom!", { add: [1150, 380, 440, "br", 40], el: "ssol" }),
    L("GERSOLDIER", "Who has the stairs?", { add: [330, 380, 400, "bl", 40], el: "gsol", cam: [["+0.15", 1.9, 960, 690, 0.6]], move: [["a-4", "+0.1", { o: 0 }, 0.2], ["a-5", "+0.1", { o: 0 }, 0.2]] }),
    N("The Soviet commander, Vasily Chuikov, had a rule for his men.", { pre: 1.8, at: ["cut-chui", "st-chui@0.55"], cam: [BACK] }),
    L("CHUIKOV", "Get closer to the Germans.", { add: [300, 430, 440, "bl", 42], el: "chui" }),
    L("SOVSOLDIER", "Closer?", { add: [1200, 470, 260, "br", 46], el: "ssol2" }),
    L("CHUIKOV", "Close enough to shake hands.", { add: [300, 430, 460, "bl", 42], el: "chui", keep: true, cam: [[0, 1.35, 700, 700, 0.4]] }),
    L("PILOT", "I can't bomb them. They're standing right next to our guys.", { add: [1000, 140, 520, "br", 38], at: ["cut-air", "pip-gp@0.05"], cam: [BACK], move: [["circle-pl", 0, { dx: -420, dy: 40 }, 4]] }),
    N("It went on like that for months.", { at: ["cut-months", "pop-m0@0.1", "pop-m1@0.4", "pop-m2@0.7"] }),
  ],
  "17": [
    N("In November, Hitler told a cheering crowd in Munich that Stalingrad was as good as taken.", { at: ["st-date"], sfx: [["cheer", 1.0]] }),
    L("HITLER", "Only a few small pockets remain!", { add: [440, 150, 480, "br", 42], el: "hitler", sfx: [["cheer", "+0.1"]], hide: ["st-date"] }),
    L("KLAUS", "Sir. One of the pockets is the river.", { pre: 0.9, add: [80, 350, 480, "bl", 40], el: "klaus", at: ["pop-inset@0.2", "pop-p1@0.65"], sfx: [["ding", -0.8]] }),
    L("HITLER", "Small pocket.", { add: [480, 170, 420, "br", 44], el: "hitler" }),
    L("KLAUS", "And the factory district.", { add: [80, 350, 440, "bl", 40], el: "klaus", at: ["pop-p2@0.35"] }),
    L("HITLER", "Small pocket!", { add: [480, 170, 420, "br", 44], el: "hitler" }),
    L("KLAUS", "And the Soviet army, sir.", { add: [80, 350, 440, "bl", 40], el: "klaus", at: ["pop-p3@0.55"], keep: true, sfx: [["slam", "+0.0"]] }),
  ],
  "18": [
    N("In November 1942, the Soviets struck the weaker Romanian armies guarding the flanks,", { at: ["st-date", "fade-rom1@0.5", "fade-rom2@0.65"] }),
    N("broke through, and met behind the city.", { at: ["arr-n", "arr-s@0.25"], sfx: [["rumble", 0], ["boom", 1.6]] }),
    N("About three hundred thousand Axis soldiers were trapped.", { at: ["pop-ring", "cnt-trap@0.5"], sfx: [["slam", 0.1]] }),
    L("KLAUS", "Sir, we're surrounded.", { add: [1000, 440, 440, "br", 40], el: "klaus", at: ["cut-hq"] }),
    L("HITLER", "The air force will fly in supplies!", { add: [300, 420, 480, "bl", 40], el: "hitler" }),
    L("KLAUS", "Sir, that's the Dunkirk promise.", { add: [1000, 440, 460, "br", 40], el: "klaus", at: ["pop-gor@0.4"] }),
    L("HITLER", "Göring promised again!", { add: [300, 430, 440, "bl", 42], el: "hitler" }),
    L("KLAUS", "The army needs about seven hundred and fifty tons a day, sir. The air force can deliver about a hundred.", { add: [1290, 150, 600, "br", 34], el: "klaus", hide: ["pop-gor"], at: ["pop-chart@0.1", "pop-bar100@0.65"] }),
    L("HITLER", "So… nearly enough.", { add: [220, 400, 400, "bl", 42], el: "hitler" }),
    L("KLAUS", "It's one seventh, sir.", { add: [1340, 420, 420, "br", 40], el: "klaus", at: ["pop-17@0.5"], keep: true, cam: [[0, 1.35, 1700, 560, 0.4]] }),
    N("Hitler forbade a breakout.", { at: ["fade-win"], cam: [BACK] }),
    N("The trapped army starved through the winter."),
  ],
  "19": [
    N("By the end of January, it was hopeless.", { at: ["st-date"] }),
    N("So Hitler had an idea.", { hide: ["st-date"] }),
    L("HITLER", "Promote Paulus to field marshal. No German field marshal has ever surrendered.", { add: [120, 400, 600, "bl", 36], el: "hitler", at: ["pop-baton@0.3"] }),
    L("KLAUS", "Sir, he's out of food. And ammunition. And army.", { add: [880, 470, 560, "br", 38], el: "klaus", at: ["pop-list", "pop-l0@0.15", "pop-l1@0.45", "pop-l2@0.8"] }),
    L("HITLER", "He'll understand the message.", { add: [160, 420, 460, "bl", 40], el: "hitler", at: ["cut-cellar@+0.3"], move: [["paulus", "+1.2", { dx: 260 }, 1.6]] }),
    L("KLAUS", "Sir… he surrendered.", { pre: 3.2, add: [1100, 450, 400, "br", 40], el: "klaus", hide: ["cut-cellar"] }),
    L("HITLER", "As a field marshal?!", { add: [180, 420, 400, "bl", 42], el: "hitler" }),
    L("KLAUS", "Brand new, sir.", { add: [1150, 460, 340, "br", 42], el: "klaus", keep: true, cam: [[0, 1.4, 1350, 720, 0.4]] }),
    N("The last Germans in the city surrendered on February 2nd, 1943.", { at: ["fade-end"], cam: [BACK], move: [["column", 0, { dx: 220 }, 9]] }),
    N("About ninety thousand German and allied soldiers went into Soviet captivity.", { at: ["cnt-pow@0.1"] }),
    N("Only around five thousand ever came home.", { at: ["cnt-home@0.1"] }),
    N("The battle cost the two sides close to two million dead, wounded and captured.", { at: ["cnt-2m@0.1"] }),
    N("Germany's war in the East would never recover."),
  ],
  "20": [
    N("In July 1943, Germany tried one last big summer attack, at Kursk, with new heavy tanks.", { cam: [[0.35, 1.8, 1071, 556, 1.0]], at: ["fade-km", "arr-kn@0.5", "arr-ks@0.55"], sfx: [["rumble", 3]] }),
    N("The Soviets knew exactly where, and were waiting behind belt after belt of minefields.", { hide: ["fade-km"], cam: [BACK], at: [...stagger("pop-belt", 5, 0.3, 0.75), "pop-sutanks@0.85"] }),
    L("KLAUS", "Sir, they knew we were coming.", { add: [1000, 470, 440, "br", 40], el: "klaus", at: ["cut-tent"] }),
    L("HITLER", "Our tanks are better!", { add: [360, 430, 440, "bl", 42], el: "hitler" }),
    L("KLAUS", "They have more tanks.", { add: [1000, 480, 420, "br", 42], el: "klaus", at: ["pop-more@0.3"] }),
    L("HITLER", "Ours are better!", { add: [360, 430, 400, "bl", 44], el: "hitler" }),
    L("KLAUS", "Ours are in the repair shop, sir.", { add: [1000, 470, 460, "br", 40], el: "klaus", at: ["cut-repair@+0.1"], sfx: [["crash", "+0.2"]] }),
    N("Germany lost one of the biggest tank battles in history.", { pre: 0.6, hide: ["cut-tent", "cut-repair"], sfx: [["boom", 0.5]] }),
    N("From then on, in the East, it only went backwards.", { at: ["fade-back", ...stagger("arr-w", 4, 0.2, 0.5)] }),
  ],
  "21": [
    N("That same month, the Allies landed in Sicily.", { cam: [[0.2, 1.8, 900, 600, 0.8]], at: ["cut-map", "arr-si1@0.3", "arr-si2@0.45"] }),
    N("Italy had had enough.", { cam: [BACK] }),
    N("Mussolini's own council turned on him, and the king had him arrested.", { at: ["cut-bal", "st-arr@0.75"] }),
    L("MUSSOLINI", "Enzo! Print \"I'm still in charge\"!", { add: [860, 180, 500, "br", 40], hide: ["cut-bal", "cut-map"], at: ["pop-mp1"] }),
    L("ENZO", "I've been fired, sir.", { add: [480, 450, 420, "br", 42], el: "enzo" }),
    N("Italy surrendered in September.", { hide: ["pop-mp1"] }),
    N("Germany occupied most of the country, broke Mussolini out of a mountain-top hotel with gliders, and set him up as a puppet in the north.", { at: ["fade-glider@0.15", "cut-puppet@0.72"], sfx: [["whoosh", 3]] }),
    L("MUSSOLINI", "Enzo?", { add: [1120, 200, 260, "br", 46], hide: ["cut-puppet", "fade-glider"], at: ["pop-mp2"] }),
    L("ENZO", "…I've been rehired.", { add: [480, 450, 400, "br", 42], move: [["enzo", 0, { o: 0 }, 0.05]], at: ["pop-unpack"], keep: true, cam: [[0, 1.35, 900, 700, 0.4]] }),
  ],
  "22": [
    N("Britain and America were bombing German cities, the British by night, the Americans by day.", { at: ["fade-night@0.35", "fade-day@0.75"] }),
    N("In July 1943, raids on Hamburg started a firestorm that killed around thirty-seven thousand people in a week.", { at: ["fade-ham", ...stagger("pop-d", 4, 0.3, 0.6), "cnt-ham@0.8"] }),
    N("The bomber crews died in huge numbers too: more than fifty-five thousand from Britain's Bomber Command alone.", { at: ["fade-crews", "cnt-bc@0.5"] }),
  ],
  "23": [
    N("In April 1943, as the Nazis came to deport the last Jews of the Warsaw Ghetto to the death camps, a few hundred young fighters with pistols and homemade bombs rose up.", { at: ["arr-wall@0.05", "fade-gfill@0.1", "fade-glabel@0.2", "pop-d1@0.3", "pop-fighters@0.7"] }),
    N("They held out for almost a month.", { at: ["pop-d2@0.1"] }),
    N("The Germans burned the ghetto to the ground.", { at: ["smoke@0.1"] }),
    N("The uprising became a lasting symbol of resistance.", { at: ["fade-candle@0.2"] }),
  ],
  "24": [
    N("In November 1943, Roosevelt, Churchill and Stalin finally met, in Tehran.", { at: ["st-date"] }),
    N("The Soviets were doing most of the dying: in the end, around twenty-seven million Soviet citizens died in the war.", { at: ["fade-27", "cnt-27@0.45"] }),
    N("Stalin had one question.", { hide: ["fade-27"] }),
    L("STALIN", "When do you invade France?", { add: [820, 280, 440, "bl", 42], el: "stalin" }),
    L("CHURCHILL", "Soon.", { add: [1300, 500, 220, "br", 48], el: "church" }),
    L("STALIN", "You said soon last year.", { add: [820, 290, 440, "bl", 42], el: "stalin" }),
    L("FDR", "May 1944.", { add: [300, 500, 300, "bl", 46], el: "fdr" }),
    L("STALIN", "I trust nobody. But I'm writing this down.", { add: [740, 250, 520, "bl", 40], el: "stalin", at: ["pop-note@0.5"], keep: true }),
    L("KLAUS", "Sir. The gauge.", { add: [1080, 450, 380, "br", 42], el: "klaus", at: ["cut-berlin"] }),
    L("HITLER", "What does it say?", { add: [300, 430, 420, "bl", 42], el: "hitler" }),
    L("KLAUS", "It says \"no.\"", { add: [1100, 450, 320, "br", 44], el: "klaus", move: [["gback", 0.3, { o: 0 }, 0.1]], at: ["pop-no@0.3"], keep: true, cam: [[0.3, 1.5, 1000, 760, 0.4]] }),
    N("The Allies were going to invade France.", { at: ["cut-where"], cam: [BACK] }),
    N("Hitler's generals thought they knew exactly where.", { at: ["arr-cal@0.4"], cam: [[0.3, 1.5, 760, 420, 0.8]] }),
    N("They were wrong.", { at: ["st-wrong@0.3", "pop-qn@0.75"], sfx: [["sting", 0.9]] }),
  ],
};
