// Adversarial recipes and matching pairs. Each case states what a SAFE product must do.
// The simulation runs them through the real verifier/matcher and reports every miss.
import type { RawRecipe } from "../src/lib/pantry/ai-output";
import type { Diet, TimeOption } from "../src/lib/pantry/schemas";

export type Attack = {
  id: string;
  area: "verification" | "constraints" | "hostile";
  attack: string;
  inventory: string[];
  maxMinutes?: TimeOption;
  diet?: Diet;
  highProtein?: boolean;
  spicy?: boolean;
  kidFriendly?: boolean;
  note?: string;
  recipe: Partial<RawRecipe> & { ingredients: RawRecipe["ingredients"]; steps: string[] };
  /** What a safe system must do. */
  safe: {
    reject?: boolean;
    notEverythingOnHand?: boolean;
    missingIncludes?: string[];
    timeShownAtLeast?: number;
  };
};

const ing = (...xs: Array<string | [string, string]>) =>
  xs.map((x) =>
    typeof x === "string" ? { name: x, measurement: "1" } : { name: x[0], measurement: x[1] },
  );

export const ATTACKS: Attack[] = [
  // ---------------------------------------------------------------- verification
  {
    id: "V01",
    area: "verification",
    attack: "step-only soy sauce",
    inventory: ["chicken", "rice"],
    recipe: {
      ingredients: ing("chicken", "rice"),
      steps: ["Cook the rice 10 minutes.", "Fry the chicken, then add soy sauce."],
    },
    safe: { notEverythingOnHand: true, missingIncludes: ["soy sauce"] },
  },
  {
    id: "V02",
    area: "verification",
    attack: "step-only butter",
    inventory: ["eggs", "bread"],
    recipe: {
      ingredients: ing("eggs", "bread"),
      steps: ["Toast the bread.", "Fry the eggs in butter 3 minutes."],
    },
    safe: { notEverythingOnHand: true, missingIncludes: ["butter"] },
  },
  {
    id: "V03",
    area: "verification",
    attack: "stated 15 min, steps total 30 (no single step over limit)",
    inventory: ["chicken", "rice"],
    maxMinutes: "15",
    recipe: {
      prepMinutes: 5,
      cookMinutes: 10,
      ingredients: ing("chicken", "rice"),
      steps: [
        "Cook the rice 10 minutes.",
        "Brown the chicken 10 minutes.",
        "Simmer together 10 minutes.",
      ],
    },
    safe: { reject: true },
  },
  {
    id: "V04",
    area: "verification",
    attack: "stated 15 min, one step 30 min",
    inventory: ["chicken", "rice"],
    maxMinutes: "15",
    recipe: {
      prepMinutes: 5,
      cookMinutes: 10,
      ingredients: ing("chicken", "rice"),
      steps: ["Simmer the chicken and rice 30 minutes."],
    },
    safe: { reject: true },
  },
  {
    id: "V05",
    area: "verification",
    attack: "2 servings but 8 eggs",
    inventory: ["eggs", "spinach"],
    recipe: {
      ingredients: ing(["eggs", "8"], "spinach"),
      steps: ["Whisk the eggs, add spinach, cook 5 minutes."],
    },
    safe: { reject: true },
  },
  {
    id: "V06",
    area: "verification",
    attack: "AI text claims 'you have everything' but an item is missing",
    inventory: ["eggs"],
    recipe: {
      description: "You already have everything for this!",
      ingredients: ing("eggs", "shallot"),
      steps: ["Cook eggs with shallot 5 minutes."],
    },
    safe: { notEverythingOnHand: true, missingIncludes: ["shallot"] },
  },
  {
    id: "V07",
    area: "verification",
    attack: "needs cream cheese, has cheese",
    inventory: ["cheese", "bagels"],
    recipe: {
      ingredients: ing("cream cheese", "bagels"),
      steps: ["Toast bagels, spread cream cheese."],
    },
    safe: { notEverythingOnHand: true, missingIncludes: ["cream cheese"] },
  },
  {
    id: "V08",
    area: "verification",
    attack: "needs coconut milk, has milk",
    inventory: ["milk", "rice"],
    recipe: {
      ingredients: ing("coconut milk", "rice"),
      steps: ["Simmer rice in coconut milk 15 minutes."],
    },
    safe: { notEverythingOnHand: true, missingIncludes: ["coconut milk"] },
  },
  {
    id: "V09",
    area: "verification",
    attack: "needs peanut butter, has butter",
    inventory: ["butter", "bread"],
    recipe: {
      ingredients: ing("peanut butter", "bread"),
      steps: ["Spread peanut butter on bread."],
    },
    safe: { notEverythingOnHand: true, missingIncludes: ["peanut butter"] },
  },
  {
    id: "V10",
    area: "verification",
    attack: "step-only ingredient outside the vocabulary (stock)",
    inventory: ["rice", "onion"],
    recipe: {
      ingredients: ing("rice", "onion"),
      steps: ["Fry the onion.", "Add the rice and pour in the stock; simmer 15 minutes."],
    },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "V11",
    area: "verification",
    attack: "step-only mirin and hoisin (not in vocabulary)",
    inventory: ["noodles", "chicken"],
    recipe: {
      ingredients: ing("noodles", "chicken"),
      steps: ["Fry chicken 6 minutes.", "Toss noodles with mirin and hoisin."],
    },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "V12",
    area: "verification",
    attack: "quantity written as '4 eggs, beaten' vs 2 listed",
    inventory: ["eggs|2"],
    recipe: { ingredients: ing(["eggs", "4 eggs, beaten"]), steps: ["Cook the eggs 3 minutes."] },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "V13",
    area: "verification",
    attack: "quantity '4 large' vs 2 listed",
    inventory: ["eggs|2"],
    recipe: { ingredients: ing(["eggs", "4 large"]), steps: ["Cook the eggs 3 minutes."] },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "V14",
    area: "verification",
    attack: "'Feeds a family of four' when 2 requested",
    inventory: ["chicken", "rice"],
    recipe: {
      description: "Feeds a family of four.",
      ingredients: ing("chicken", "rice"),
      steps: ["Cook 15 minutes."],
    },
    safe: { reject: true },
  },
  {
    id: "V15",
    area: "verification",
    attack: "'Serves 4' when 2 requested",
    inventory: ["chicken", "rice"],
    recipe: {
      description: "Serves 4.",
      ingredients: ing("chicken", "rice"),
      steps: ["Cook 15 minutes."],
    },
    safe: { reject: true },
  },
  {
    id: "V16",
    area: "verification",
    attack: "'about an hour' in a 30-min request",
    inventory: ["beef", "onion"],
    maxMinutes: "30",
    recipe: { ingredients: ing("beef", "onion"), steps: ["Simmer until tender, about an hour."] },
    safe: { reject: true },
  },
  {
    id: "V17",
    area: "verification",
    attack: "'rest overnight' in a 45-min request",
    inventory: ["chicken"],
    maxMinutes: "45",
    recipe: {
      ingredients: ing("chicken"),
      steps: ["Marinate the chicken; rest overnight.", "Grill 10 minutes."],
    },
    safe: { reject: true },
  },
  {
    id: "V18",
    area: "verification",
    attack: "time written as 'twenty-five minutes' in a 15-min request",
    inventory: ["pasta"],
    maxMinutes: "15",
    recipe: { ingredients: ing("pasta"), steps: ["Boil the pasta for twenty-five minutes."] },
    safe: { reject: true },
  },
  {
    id: "V19",
    area: "verification",
    attack: "swap suggests an item the user also lacks",
    inventory: ["eggs"],
    recipe: {
      ingredients: ing("eggs", "heavy cream"),
      steps: ["Whisk eggs and cream."],
      substitutes: [{ from: "heavy cream", to: "half and half" }],
    },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "V20",
    area: "verification",
    attack: "generic 'oil' on list, step uses sesame oil",
    inventory: ["oil", "rice", "eggs"],
    recipe: {
      ingredients: ing("oil", "rice", "eggs"),
      steps: ["Fry the rice and eggs in oil 5 minutes.", "Finish with sesame oil."],
    },
    safe: { notEverythingOnHand: true, missingIncludes: ["sesame oil"] },
  },

  // ---------------------------------------------------------------- constraints
  {
    id: "C01",
    area: "constraints",
    attack: "no mushrooms; mushrooms only in step 5",
    note: "no mushrooms",
    inventory: ["chicken", "rice", "onion"],
    recipe: {
      ingredients: ing("chicken", "rice", "onion"),
      steps: [
        "Cook rice.",
        "Fry onion.",
        "Add chicken.",
        "Stir.",
        "Add sliced mushrooms and cook 5 minutes.",
      ],
    },
    safe: { reject: true },
  },
  {
    id: "C02",
    area: "constraints",
    attack: "vegetarian; bacon in step 4",
    diet: "Vegetarian",
    inventory: ["eggs", "spinach"],
    recipe: {
      ingredients: ing("eggs", "spinach"),
      steps: ["Whisk eggs.", "Wilt spinach.", "Combine.", "Crumble bacon over the top."],
    },
    safe: { reject: true },
  },
  {
    id: "C03",
    area: "constraints",
    attack: "vegetarian; bacon as an OPTIONAL garnish",
    diet: "Vegetarian",
    inventory: ["eggs", "spinach"],
    recipe: {
      ingredients: ing("eggs", "spinach"),
      steps: ["Scramble eggs with spinach 4 minutes.", "Optional: top with crispy bacon."],
    },
    safe: { reject: true },
  },
  {
    id: "C04",
    area: "constraints",
    attack: "no dairy; cheddar hidden in a step",
    note: "no dairy",
    inventory: ["eggs", "potatoes"],
    recipe: {
      ingredients: ing("eggs", "potatoes"),
      steps: ["Boil potatoes 15 minutes.", "Mash and fold in grated cheddar."],
    },
    safe: { reject: true },
  },
  {
    id: "C05",
    area: "constraints",
    attack: "no dairy; cheddar as 'if you like'",
    note: "no dairy",
    inventory: ["eggs", "potatoes"],
    recipe: {
      ingredients: ing("eggs", "potatoes"),
      steps: ["Boil potatoes 15 minutes.", "If you like, sprinkle with cheddar."],
    },
    safe: { reject: true },
  },
  {
    id: "C06",
    area: "constraints",
    attack: "high protein; no meaningful protein",
    highProtein: true,
    inventory: ["rice", "green beans"],
    recipe: {
      ingredients: ing("rice", "green beans"),
      steps: ["Cook rice 12 minutes.", "Steam beans."],
    },
    safe: { reject: true },
  },
  {
    id: "C07",
    area: "constraints",
    attack: "high protein; only 'egg noodles' as protein evidence",
    highProtein: true,
    inventory: ["egg noodles", "broccoli"],
    recipe: {
      ingredients: ing("egg noodles", "broccoli"),
      steps: ["Boil noodles 8 minutes, toss with broccoli."],
    },
    safe: { reject: true },
  },
  {
    id: "C08",
    area: "constraints",
    attack: "'no spicy food'; hot sauce hidden in steps",
    note: "no spicy food",
    inventory: ["chicken", "rice"],
    recipe: {
      ingredients: ing("chicken", "rice"),
      steps: ["Cook rice 12 minutes.", "Toss chicken with a dash of hot sauce."],
    },
    safe: { reject: true },
  },
  {
    id: "C09",
    area: "constraints",
    attack: "'not spicy'; hot sauce hidden in steps",
    note: "not spicy",
    inventory: ["chicken", "rice"],
    recipe: {
      ingredients: ing("chicken", "rice"),
      steps: ["Cook rice 12 minutes.", "Toss chicken with a dash of hot sauce."],
    },
    safe: { reject: true },
  },
  {
    id: "C10",
    area: "constraints",
    attack: "kid-friendly; chili powder in steps",
    kidFriendly: true,
    inventory: ["chicken", "rice"],
    recipe: {
      ingredients: ing("chicken", "rice"),
      steps: ["Rub chicken with chili powder, cook 10 minutes."],
    },
    safe: { reject: true },
  },
  {
    id: "C11",
    area: "constraints",
    attack: "vegan; ghee only in the steps",
    diet: "Vegan",
    inventory: ["lentils", "onion"],
    recipe: {
      ingredients: ing("lentils", "onion"),
      steps: ["Fry onion in ghee.", "Add lentils, simmer 20 minutes."],
    },
    safe: { reject: true },
  },
  {
    id: "C12",
    area: "constraints",
    attack: "vegan; honey only in the steps",
    diet: "Vegan",
    inventory: ["oats", "bananas"],
    recipe: {
      ingredients: ing("oats", "bananas"),
      steps: ["Cook oats 5 minutes.", "Top with banana and honey."],
    },
    safe: { reject: true },
  },
  {
    id: "C13",
    area: "constraints",
    attack: "vegetarian; bare 'worcestershire' in steps",
    diet: "Vegetarian",
    inventory: ["mushrooms", "onion"],
    recipe: {
      ingredients: ing("mushrooms", "onion"),
      steps: ["Fry mushrooms and onion 8 minutes with a splash of worcestershire."],
    },
    safe: { reject: true },
  },
  {
    id: "C14",
    area: "constraints",
    attack: "vegetarian; 'lardons' (not in meat list)",
    diet: "Vegetarian",
    inventory: ["lardons", "potatoes"],
    recipe: {
      ingredients: ing("lardons", "potatoes"),
      steps: ["Fry lardons and potatoes 15 minutes."],
    },
    safe: { reject: true },
  },
  {
    id: "C15",
    area: "constraints",
    attack: "gluten-free; beer in steps",
    diet: "Gluten-free",
    inventory: ["chicken", "onion"],
    recipe: {
      ingredients: ing("chicken", "onion"),
      steps: ["Braise chicken and onion in beer 20 minutes."],
    },
    safe: { reject: true },
  },
  {
    id: "C16",
    area: "constraints",
    attack: "gluten-free; soy sauce in steps",
    diet: "Gluten-free",
    inventory: ["rice", "eggs"],
    recipe: {
      ingredients: ing("rice", "eggs"),
      steps: ["Fry rice and eggs, season with soy sauce."],
    },
    safe: { reject: true },
  },
  {
    id: "C17",
    area: "constraints",
    attack: "nut-free; pine nuts in steps",
    note: "nut-free",
    inventory: ["pasta", "basil"],
    recipe: {
      ingredients: ing("pasta", "basil"),
      steps: ["Boil pasta 10 minutes.", "Blend basil with pine nuts."],
    },
    safe: { reject: true },
  },
  {
    id: "C18",
    area: "constraints",
    attack: "'no pork'; pancetta listed",
    note: "no pork",
    inventory: ["pasta", "pancetta"],
    recipe: { ingredients: ing("pasta", "pancetta"), steps: ["Crisp pancetta, toss with pasta."] },
    safe: { reject: true },
  },
  {
    id: "C19",
    area: "constraints",
    attack: "servings=2 but AI states servings 4",
    inventory: ["chicken", "rice"],
    recipe: { servings: 4, ingredients: ing("chicken", "rice"), steps: ["Cook 15 minutes."] },
    safe: { reject: true },
  },
  {
    id: "C20",
    area: "constraints",
    attack: "60+ request; 5-hour braise",
    maxMinutes: "60+",
    inventory: ["beef", "onion"],
    recipe: { ingredients: ing("beef", "onion"), steps: ["Braise for 5 hours."] },
    safe: { reject: true },
  },

  // ---------------------------------------------------------------- hostile inputs (fail safe expected)
  {
    id: "H01",
    area: "hostile",
    attack: "vague list item 'sauce' used as an ingredient",
    inventory: ["sauce", "pasta"],
    recipe: { ingredients: ing("sauce", "pasta"), steps: ["Boil pasta 10 minutes and add sauce."] },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "H02",
    area: "hostile",
    attack: "list item 'leftovers' used as 'leftover chicken'",
    inventory: ["leftovers", "rice"],
    recipe: {
      ingredients: ing("leftover chicken", "rice"),
      steps: ["Reheat the chicken and rice 5 minutes."],
    },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "H03",
    area: "hostile",
    attack: "'meat' on list, recipe needs chicken breast",
    inventory: ["meat", "rice"],
    recipe: { ingredients: ing("chicken breast", "rice"), steps: ["Cook 15 minutes."] },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "H04",
    area: "hostile",
    attack: "brand 'Philadelphia' on list, recipe needs cream cheese",
    inventory: ["Philadelphia", "bagels"],
    recipe: {
      ingredients: ing("cream cheese", "bagels"),
      steps: ["Spread cream cheese on bagels."],
    },
    safe: { missingIncludes: ["cream cheese"] },
  },
  {
    id: "H05",
    area: "hostile",
    attack: "'sweet potatoes' on list, recipe needs potatoes",
    inventory: ["sweet potatoes", "butter"],
    recipe: {
      ingredients: ing("potatoes", "butter"),
      steps: ["Boil potatoes 15 minutes, mash with butter."],
    },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "H06",
    area: "hostile",
    attack: "'chicken nuggets' on list, recipe needs chicken",
    inventory: ["chicken nuggets", "rice"],
    recipe: { ingredients: ing("chicken", "rice"), steps: ["Cook chicken and rice 15 minutes."] },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "H07",
    area: "hostile",
    attack: "'milk chocolate' on list, recipe needs milk",
    inventory: ["milk chocolate", "oats"],
    recipe: { ingredients: ing("milk", "oats"), steps: ["Cook oats in milk 5 minutes."] },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "H08",
    area: "hostile",
    attack: "'condensed milk' on list, recipe needs milk",
    inventory: ["condensed milk", "oats"],
    recipe: { ingredients: ing("milk", "oats"), steps: ["Cook oats in milk 5 minutes."] },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "H09",
    area: "hostile",
    attack: "'egg noodles' on list, recipe needs eggs",
    inventory: ["egg noodles", "spinach"],
    recipe: {
      ingredients: ing("eggs", "spinach"),
      steps: ["Scramble eggs with spinach 4 minutes."],
    },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "H10",
    area: "hostile",
    attack: "'green beans' on list, recipe needs black beans",
    inventory: ["green beans", "rice"],
    recipe: { ingredients: ing("beans", "rice"), steps: ["Simmer beans and rice 15 minutes."] },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "H11",
    area: "hostile",
    attack: "'green onions' on list, recipe needs onion",
    inventory: ["green onions", "eggs"],
    recipe: { ingredients: ing("onion", "eggs"), steps: ["Fry onion 5 minutes, add eggs."] },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "H12",
    area: "hostile",
    attack: "'frozen yogurt' on list, recipe needs yogurt",
    inventory: ["frozen yogurt", "cucumber"],
    recipe: { ingredients: ing("yogurt", "cucumber"), steps: ["Mix yogurt and grated cucumber."] },
    safe: { notEverythingOnHand: true },
  },
  {
    id: "H13",
    area: "hostile",
    attack: "impossible time: 60+ request, stated 0 minutes",
    maxMinutes: "60+",
    inventory: ["eggs"],
    recipe: { prepMinutes: 0, cookMinutes: 0, ingredients: ing("eggs"), steps: ["Eat the eggs."] },
    safe: { reject: true },
  },
  {
    id: "H14",
    area: "hostile",
    attack: "contradictory constraints: vegan + high protein, only honey + oats",
    diet: "Vegan",
    highProtein: true,
    inventory: ["oats", "honey"],
    recipe: { ingredients: ing("oats", "honey"), steps: ["Cook oats 5 minutes with honey."] },
    safe: { reject: true },
  },
  {
    id: "H15",
    area: "hostile",
    attack: "spicy + kid-friendly together (contradiction)",
    spicy: true,
    kidFriendly: true,
    inventory: ["chicken", "jalapeno"],
    recipe: {
      ingredients: ing("chicken", "jalapeno"),
      steps: ["Cook chicken with jalapeno 10 minutes."],
    },
    safe: {},
  },
];

/** Inventory item satisfies recipe ingredient? must / must-not / either (debatable, not scored). */
export const MATCH_PAIRS: Array<
  [inventory: string, recipe: string, expect: "must" | "must-not" | "either"]
> = [
  ["egg", "eggs", "must"],
  ["eggs", "egg", "must"],
  ["tomato", "tomatoes", "must"],
  ["tomatoes", "tomato", "must"],
  ["scallion", "green onion", "must"],
  ["green onion", "scallions", "must"],
  ["cilantro", "coriander", "must"],
  ["coriander", "cilantro", "must"],
  ["zucchini", "courgette", "must"],
  ["courgette", "zucchini", "must"],
  ["cheddar", "cheddar cheese", "must"],
  ["cheddar cheese", "cheddar", "must"],
  ["chicken breast", "chicken", "must"],
  ["capsicum", "bell pepper", "must"],
  ["prawns", "shrimp", "must"],
  ["aubergine", "eggplant", "must"],
  ["garbanzo beans", "chickpeas", "must"],
  ["double cream", "heavy cream", "must"],
  ["yoghurt", "yogurt", "must"],
  ["rocket", "arugula", "must"],
  ["icing sugar", "powdered sugar", "must"],
  ["beef mince", "ground beef", "must"],
  ["olive oil", "oil", "must"],
  ["mozzarella", "cheese", "must"],
  ["spaghetti", "pasta", "must"],
  ["lemons", "lemon juice", "must"],
  ["garlic", "garlic cloves", "must"],
  ["large eggs", "eggs", "must"],
  ["red onion", "onion", "must"],
  ["baby spinach", "spinach", "must"],
  ["jalapeño", "jalapeno", "must"],
  ["potatoes", "potato", "must"],
  ["cornflour", "cornstarch", "must"],
  ["turkey mince", "ground turkey", "must"],
  ["salad leaves", "mixed greens", "must"],
  ["tinned tomatoes", "canned tomatoes", "must"],
  ["milk", "coconut milk", "must-not"],
  ["coconut milk", "milk", "must-not"],
  ["milk", "almond milk", "must-not"],
  ["almond milk", "milk", "must-not"],
  ["oat milk", "milk", "must-not"],
  ["butter", "peanut butter", "must-not"],
  ["peanut butter", "butter", "must-not"],
  ["cheese", "cream cheese", "must-not"],
  ["cream cheese", "cheese", "must-not"],
  ["cottage cheese", "cheese", "must-not"],
  ["cream", "ice cream", "must-not"],
  ["ice cream", "cream", "must-not"],
  ["cream", "sour cream", "must-not"],
  ["chicken", "chicken broth", "must-not"],
  ["chicken broth", "chicken", "must-not"],
  ["chicken stock", "chicken", "must-not"],
  ["beef broth", "beef", "must-not"],
  ["oil", "sesame oil", "must-not"],
  ["sesame oil", "olive oil", "must-not"],
  ["flour", "almond flour", "must-not"],
  ["almond flour", "flour", "must-not"],
  ["tomatoes", "tomato paste", "must-not"],
  ["tomato paste", "tomatoes", "must-not"],
  ["garlic powder", "garlic", "must-not"],
  ["onion powder", "onion", "must-not"],
  ["chili powder", "chili", "must-not"],
  ["rice vinegar", "rice", "must-not"],
  ["rice noodles", "rice", "must-not"],
  ["coconut", "coconut milk", "must-not"],
  ["peanuts", "peanut butter", "must-not"],
  ["eggs", "eggplant", "must-not"],
  ["butter", "butternut squash", "must-not"],
  ["pepper", "bell pepper", "must-not"],
  ["corn", "cornstarch", "must-not"],
  ["sweet potatoes", "potatoes", "must-not"],
  ["potatoes", "sweet potatoes", "must-not"],
  ["green beans", "beans", "must-not"],
  ["green onions", "onion", "must-not"],
  ["chicken nuggets", "chicken", "must-not"],
  ["milk chocolate", "milk", "must-not"],
  ["condensed milk", "milk", "must-not"],
  ["chocolate milk", "milk", "must-not"],
  ["egg noodles", "eggs", "must-not"],
  ["frozen yogurt", "yogurt", "must-not"],
  ["greek yogurt", "sour cream", "must-not"],
  ["sour cream", "greek yogurt", "must-not"],
  ["lemons", "limes", "must-not"],
  ["parsley", "cilantro", "must-not"],
  ["sugar", "salt", "must-not"],
  ["heavy cream", "milk", "must-not"],
  ["milk", "heavy cream", "must-not"],
  ["cucumber", "zucchini", "must-not"],
  ["tomato soup", "tomato", "must-not"],
  ["fish sauce", "fish", "must-not"],
  ["pasta sauce", "pasta", "must-not"],
  ["vanilla ice cream", "vanilla", "must-not"],
  ["almonds", "almond milk", "must-not"],
  ["cilantro", "ground coriander", "must-not"],
  ["rice cakes", "rice", "must-not"],
  ["hot dogs", "hot sauce", "must-not"],
  ["chicken", "chicken breast", "either"],
  ["greek yogurt", "yogurt", "either"],
  ["yogurt", "greek yogurt", "either"],
  ["black beans", "beans", "either"],
  ["sugar", "brown sugar", "either"],
  ["apples", "apple juice", "either"],
  ["roast chicken", "chicken", "either"],
  ["evaporated milk", "milk", "either"],
];
