// SYNTHETIC kitchens for the adversarial simulation. Hand-written, realistic inventories.
// This is ground truth for the SIMULATION only — it is not real user data and says nothing
// about real vision accuracy.
export type TruthItem = { name: string; qty?: string; packaged?: boolean };
export type Kitchen = { id: string; archetype: string; truth: TruthItem[] };

const k = (id: string, archetype: string, items: Array<string | TruthItem>): Kitchen => ({
  id,
  archetype,
  truth: items.map((i) => (typeof i === "string" ? { name: i } : i)),
});
const p = (name: string, qty?: string): TruthItem => ({ name, qty, packaged: true });
const q = (name: string, qty: string): TruthItem => ({ name, qty });

export const KITCHENS: Kitchen[] = [
  k("k01", "nearly empty fridge", [q("eggs", "2"), "butter", "ketchup"]),
  k("k02", "normal family fridge", [
    q("eggs", "12"),
    "milk",
    "cheddar cheese",
    "chicken breast",
    "carrots",
    "broccoli",
    "butter",
    "apples",
    "greek yogurt",
    "ham",
    "lettuce",
    "orange juice",
  ]),
  k("k03", "extremely crowded fridge", [
    q("eggs", "8"),
    "milk",
    "heavy cream",
    "cheddar cheese",
    "mozzarella",
    "parmesan",
    "chicken thighs",
    "ground beef",
    "bacon",
    "spinach",
    "kale",
    "bell peppers",
    "zucchini",
    "mushrooms",
    "cherry tomatoes",
    "cucumber",
    "lemons",
    "limes",
    "green onions",
    "cilantro",
    "ginger",
    "garlic",
    "sour cream",
    "greek yogurt",
    "butter",
    "hummus",
    "salsa",
    "soy sauce",
    "sriracha",
    "mayonnaise",
    "mustard",
    "tortillas",
  ]),
  k("k04", "college fridge", [
    p("instant ramen", "3"),
    "hot sauce",
    "leftover pizza",
    q("eggs", "3"),
    "shredded cheese",
    "energy drinks",
    "ketchup",
  ]),
  k("k05", "pantry-heavy kitchen", [
    "rice",
    "pasta",
    p("canned tomatoes"),
    p("canned chickpeas"),
    p("black beans"),
    "lentils",
    "flour",
    "sugar",
    "olive oil",
    "onions",
    "garlic",
    "potatoes",
    p("tuna"),
    p("peanut butter"),
    "oats",
    p("chicken broth"),
  ]),
  k("k06", "vegetarian kitchen", [
    "tofu",
    "tempeh",
    "chickpeas",
    "spinach",
    "sweet potatoes",
    "quinoa",
    "black beans",
    "avocado",
    "feta",
    q("eggs", "6"),
    "lentils",
    "coconut milk",
    "curry paste",
    "brown rice",
  ]),
  k("k07", "high-protein kitchen", [
    "chicken breast",
    "ground turkey",
    q("eggs", "18"),
    "greek yogurt",
    "cottage cheese",
    "tuna",
    "protein powder",
    "salmon",
    "broccoli",
    "rice",
    "oats",
    "almonds",
  ]),
  k("k08", "leftover-heavy kitchen", [
    "leftover rice",
    "roast chicken",
    "leftover chili",
    "cooked pasta",
    "half an onion",
    "cheddar cheese",
    "sour cream",
    "tortillas",
  ]),
  k("k09", "breakfast-heavy", [
    q("eggs", "12"),
    "bacon",
    "bread",
    "butter",
    "milk",
    "maple syrup",
    "pancake mix",
    "blueberries",
    "bananas",
    "yogurt",
    "granola",
    "orange juice",
  ]),
  k("k10", "Mexican-style set", [
    "tortillas",
    "black beans",
    "ground beef",
    "cheddar cheese",
    "salsa",
    "jalapenos",
    "avocado",
    "limes",
    "cilantro",
    "onion",
    "sour cream",
    "rice",
    "cumin",
    "chili powder",
  ]),
  k("k11", "Asian-style set", [
    "rice",
    "soy sauce",
    "sesame oil",
    "rice vinegar",
    "ginger",
    "garlic",
    "green onions",
    "tofu",
    "bok choy",
    q("eggs", "6"),
    "chicken thighs",
    "gochujang",
    "noodles",
    "mirin",
  ]),
  k("k12", "Italian-style set", [
    "spaghetti",
    "canned tomatoes",
    "garlic",
    "olive oil",
    "parmesan",
    "basil",
    "mozzarella",
    "onion",
    "ground beef",
    "oregano",
    "red wine",
    "tomato paste",
  ]),
  k("k13", "baking-heavy pantry", [
    "flour",
    "sugar",
    "brown sugar",
    "baking powder",
    "baking soda",
    "vanilla",
    "butter",
    q("eggs", "6"),
    "milk",
    "chocolate chips",
    "cocoa powder",
    "powdered sugar",
    "almond flour",
  ]),
  k("k14", "frozen-food-heavy", [
    p("frozen peas"),
    p("frozen chicken nuggets"),
    p("frozen pizza"),
    p("frozen mixed vegetables"),
    p("frozen shrimp"),
    p("ice cream"),
    p("frozen berries"),
    p("french fries"),
  ]),
  k("k15", "lots of condiments", [
    "ketchup",
    "mustard",
    "mayonnaise",
    "soy sauce",
    "hot sauce",
    "sriracha",
    "bbq sauce",
    "ranch dressing",
    "pickles",
    "relish",
    "hoisin sauce",
    "fish sauce",
    "worcestershire sauce",
    q("eggs", "4"),
    "bread",
  ]),
  k("k16", "duplicate ingredients (several of the same)", [
    q("eggs", "18"),
    "cheddar cheese",
    "mozzarella",
    "milk",
    "whole milk",
    "chicken breast",
    "chicken thighs",
    "onion",
    "red onion",
  ]),
  k("k17", "brand-name products", [
    p("cream cheese"),
    p("mayonnaise"),
    p("ketchup"),
    p("greek yogurt"),
    p("sriracha"),
    p("peanut butter"),
    p("parmesan"),
    "bagels",
    p("hot sauce"),
  ]),
  k("k18", "partially visible packaged food", [
    p("tortillas"),
    p("shredded mozzarella"),
    p("pesto"),
    "spinach",
    p("hummus"),
    "chicken breast",
    p("coconut milk"),
  ]),
  k("k19", "ambiguous ingredients", [
    "leftover soup",
    "cooked rice",
    "pesto",
    "chicken stock",
    "cream",
    "shredded cheese",
    "mixed greens",
  ]),
  k("k20", "very small ingredient set", ["pasta", "butter", "parmesan"]),
  k("k21", "vegan kitchen", [
    "tofu",
    "almond milk",
    "oat milk",
    "nutritional yeast",
    "chickpeas",
    "spinach",
    "rice",
    "peanut butter",
    "bananas",
    "coconut milk",
    "tahini",
    "lentils",
  ]),
  k("k22", "gluten-free household", [
    "rice noodles",
    "tamari",
    "quinoa",
    "corn tortillas",
    "chicken breast",
    "bell peppers",
    "rice",
    q("eggs", "6"),
    "potatoes",
    "almond flour",
  ]),
  k("k23", "single-person minimal", ["bread", "peanut butter", "bananas", "milk", q("eggs", "2")]),
  k("k24", "keto/low-carb", [
    "bacon",
    q("eggs", "12"),
    "avocado",
    "heavy cream",
    "cheddar cheese",
    "spinach",
    "butter",
    "salmon",
    "cauliflower",
    "cream cheese",
  ]),
  k("k25", "Indian-style set", [
    "basmati rice",
    "lentils",
    "chickpeas",
    "onion",
    "garlic",
    "ginger",
    "tomatoes",
    "garam masala",
    "turmeric",
    "cumin",
    "coconut milk",
    "paneer",
    "spinach",
    "ghee",
    "yogurt",
  ]),
  k("k26", "Mediterranean set", [
    "feta",
    "olives",
    "cucumber",
    "tomatoes",
    "red onion",
    "chickpeas",
    "lemons",
    "olive oil",
    "pita",
    "hummus",
    "oregano",
    "greek yogurt",
  ]),
  k("k27", "BBQ / grill kitchen", [
    "ground beef",
    "hot dogs",
    "burger buns",
    "cheddar cheese",
    "bbq sauce",
    "corn",
    "potatoes",
    "onion",
    "lettuce",
    "tomatoes",
    "pickles",
  ]),
  k("k28", "seafood-focused", [
    "salmon",
    "shrimp",
    "cod",
    "lemons",
    "garlic",
    "butter",
    "parsley",
    "rice",
    "asparagus",
    "white wine",
  ]),
  k("k29", "kid-focused family", [
    "chicken nuggets",
    "macaroni",
    "cheddar cheese",
    "milk",
    "apples",
    "carrots",
    "peanut butter",
    "bread",
    "yogurt",
    "hot dogs",
  ]),
  k("k30", "health-food kitchen", [
    "kale",
    "quinoa",
    "chia seeds",
    "almond milk",
    "blueberries",
    "avocado",
    "salmon",
    "sweet potatoes",
    "greek yogurt",
    "walnuts",
  ]),
  k("k31", "post-grocery-run haul", [
    "chicken breast",
    "ground beef",
    "salmon",
    "rice",
    "pasta",
    q("eggs", "12"),
    "milk",
    "butter",
    "cheddar cheese",
    "spinach",
    "broccoli",
    "carrots",
    "onions",
    "garlic",
    "potatoes",
    "apples",
    "bananas",
    "bread",
    "yogurt",
    "tomatoes",
    "lettuce",
    "bell peppers",
  ]),
  k("k32", "end-of-week scraps", [
    "half a lemon",
    "wilted spinach",
    q("eggs", "1"),
    "stale bread",
    "parmesan",
  ]),
  k("k33", "soup-maker", [
    "chicken stock",
    "vegetable stock",
    "carrots",
    "celery",
    "onions",
    "potatoes",
    "lentils",
    "canned tomatoes",
    "barley",
    "thyme",
    "bay leaves",
  ]),
  k("k34", "sandwich station", [
    "bread",
    "turkey",
    "ham",
    "swiss cheese",
    "lettuce",
    "tomatoes",
    "mayonnaise",
    "mustard",
    "pickles",
  ]),
  k("k35", "dairy-heavy", [
    "milk",
    "heavy cream",
    "sour cream",
    "cream cheese",
    "butter",
    "cheddar cheese",
    "mozzarella",
    "ricotta",
    "parmesan",
    "yogurt",
    "cottage cheese",
  ]),
  k("k36", "Thai-style set", [
    "coconut milk",
    "red curry paste",
    "fish sauce",
    "jasmine rice",
    "chicken thighs",
    "lemongrass",
    "limes",
    "basil",
    "bell peppers",
    "peanuts",
    "rice noodles",
  ]),
  k("k37", "Middle Eastern pantry", [
    "tahini",
    "chickpeas",
    "bulgur",
    "lentils",
    "sumac",
    "za'atar",
    "pomegranate molasses",
    "lemons",
    "parsley",
    "mint",
    "pita",
    "lamb mince",
  ]),
  k("k38", "similar-looking jars", [
    "greek yogurt",
    "sour cream",
    "cream cheese",
    "mayonnaise",
    "hummus",
    "ricotta",
  ]),
  k("k39", "similar-looking produce", [
    "parsley",
    "cilantro",
    "green onions",
    "leeks",
    "limes",
    "lemons",
    "zucchini",
    "cucumber",
  ]),
  k("k40", "oil & vinegar shelf", [
    "olive oil",
    "sesame oil",
    "vegetable oil",
    "balsamic vinegar",
    "rice vinegar",
    "coconut oil",
    "garlic",
    "onion",
    "pasta",
  ]),
  k("k41", "flour shelf", [
    "flour",
    "almond flour",
    "cornstarch",
    "sugar",
    "baking powder",
    q("eggs", "3"),
    "butter",
    "milk",
  ]),
  k("k42", "milks galore", [
    "milk",
    "almond milk",
    "oat milk",
    "coconut milk",
    "cereal",
    "oats",
    "bananas",
  ]),
  k("k43", "brothy pantry", [
    "chicken broth",
    "beef broth",
    "rice",
    "pasta",
    "onion",
    "garlic",
    "canned beans",
    "chicken breast",
  ]),
  k("k44", "spice-forward kitchen", [
    "chili powder",
    "cayenne",
    "paprika",
    "cumin",
    "chicken thighs",
    "rice",
    "black beans",
    "jalapenos",
    "hot sauce",
    "limes",
    "onion",
  ]),
  k("k45", "mild family kitchen", [
    "chicken breast",
    "rice",
    "carrots",
    "peas",
    "butter",
    "milk",
    "cheddar cheese",
    "pasta",
    "broccoli",
  ]),
  k("k46", "meal-prep containers", [
    "cooked chicken",
    "cooked rice",
    "roasted vegetables",
    "cooked quinoa",
    "black beans",
    "salsa",
    "greek yogurt",
  ]),
  k("k47", "Korean pantry", [
    "kimchi",
    "gochujang",
    "rice",
    "tofu",
    "green onions",
    q("eggs", "6"),
    "sesame oil",
    "soy sauce",
    "pork belly",
    "garlic",
  ]),
  k("k48", "brunch party leftovers", [
    "bagels",
    "cream cheese",
    "smoked salmon",
    "capers",
    "red onion",
    "orange juice",
    "croissants",
    "strawberries",
  ]),
  k("k49", "picky-eater kitchen", [
    "pasta",
    "butter",
    "cheddar cheese",
    "chicken nuggets",
    "bread",
    "milk",
  ]),
  k("k50", "bulk-buyer pantry", [
    "rice",
    "dried beans",
    "oats",
    "flour",
    "sugar",
    "peanut butter",
    "canned tomatoes",
    "canned tuna",
    "pasta",
    "olive oil",
    "honey",
    "coffee",
  ]),
  k("k51", "herb garden kitchen", [
    "basil",
    "mint",
    "rosemary",
    "thyme",
    "parsley",
    "cherry tomatoes",
    "garlic",
    "olive oil",
    "pasta",
    "lemons",
  ]),
  k("k52", "holiday leftovers", [
    "roast turkey",
    "stuffing",
    "mashed potatoes",
    "cranberry sauce",
    "gravy",
    "green beans",
    "rolls",
  ]),
];
